//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace FixPortal.FixAtdl.Resources {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [DebuggerNonUserCode()]
    [CompilerGenerated()]
    internal class HumanReadableTypeNames {
        
        private static ResourceManager resourceMan;
        
        private static CultureInfo resourceCulture;
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HumanReadableTypeNames() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static ResourceManager ResourceManager {
            get {
                if (ReferenceEquals(resourceMan, null)) {
                    ResourceManager temp = new ResourceManager("FixPortal.FixAtdl.Resources.HumanReadableTypeNames", typeof(HumanReadableTypeNames).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to boolean value.
        /// </summary>
        internal static string BooleanType {
            get {
                return ResourceManager.GetString("BooleanType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to char value.
        /// </summary>
        internal static string CharType {
            get {
                return ResourceManager.GetString("CharType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to country code.
        /// </summary>
        internal static string CountryType {
            get {
                return ResourceManager.GetString("CountryType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to currency.
        /// </summary>
        internal static string CurrencyType {
            get {
                return ResourceManager.GetString("CurrencyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to data value.
        /// </summary>
        internal static string DataType {
            get {
                return ResourceManager.GetString("DataType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to date.
        /// </summary>
        internal static string DateType {
            get {
                return ResourceManager.GetString("DateType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to exchange code.
        /// </summary>
        internal static string ExchangeType {
            get {
                return ResourceManager.GetString("ExchangeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to language.
        /// </summary>
        internal static string LanguageType {
            get {
                return ResourceManager.GetString("LanguageType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to month-year value.
        /// </summary>
        internal static string MonthYearType {
            get {
                return ResourceManager.GetString("MonthYearType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to number.
        /// </summary>
        internal static string NumericType {
            get {
                return ResourceManager.GetString("NumericType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to string.
        /// </summary>
        internal static string StringType {
            get {
                return ResourceManager.GetString("StringType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tenor value.
        /// </summary>
        internal static string TenorType {
            get {
                return ResourceManager.GetString("TenorType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to date/time.
        /// </summary>
        internal static string TimestampType {
            get {
                return ResourceManager.GetString("TimestampType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to time.
        /// </summary>
        internal static string TimeType {
            get {
                return ResourceManager.GetString("TimeType", resourceCulture);
            }
        }
    }
}

