// NOTE: This file is generated from the FIX 5.0 SP2 field dictionary
// (fixportal-quickfixn/spec/fix/FIX50SP2.xml <fields> section, a later version being a strict
// superset of earlier ones). Editing by hand is not recommended; regenerate instead.

namespace FixPortal.FixAtdl.Fix;

/// <summary>
/// Classifies each <see cref="FixField"/> by whether its FIX data type is numeric (Int, Length,
/// TagNum, SeqNum, NumInGroup, Qty, Price, PriceOffset, Amt, Float, Percentage) or not (String,
/// Char, Boolean, Currency, Exchange, Data, MultipleCharValue, MultipleStringValue, Country,
/// Language, MonthYear, and the UTC/local date-time types). Used to decide whether a FIX_ field's
/// value should be treated as a number for comparison purposes, rather than guessing from whether
/// the text happens to parse as a decimal - a guess that misclassifies a numeric-looking String/Char
/// field (e.g. a zero-padded ClOrdID) as a number.
/// </summary>
public static class FixFieldTypes
{
    private static readonly Dictionary<FixField, bool> IsNumericByField = new()
    {
        { FixField.FIX_Account, false }, // STRING
        { FixField.FIX_AccountType, true }, // INT
        { FixField.FIX_AccruedInterestAmt, true }, // AMT
        { FixField.FIX_AccruedInterestRate, true }, // PERCENTAGE
        { FixField.FIX_AcctIDSource, true }, // INT
        { FixField.FIX_Adjustment, true }, // INT
        { FixField.FIX_AdjustmentType, true }, // INT
        { FixField.FIX_AdvId, false }, // STRING
        { FixField.FIX_AdvRefID, false }, // STRING
        { FixField.FIX_AdvSide, false }, // CHAR
        { FixField.FIX_AdvTransType, false }, // STRING
        { FixField.FIX_AffectedOrderID, false }, // STRING
        { FixField.FIX_AffectedSecondaryOrderID, false }, // STRING
        { FixField.FIX_AffirmStatus, true }, // INT
        { FixField.FIX_AggregatedBook, false }, // BOOLEAN
        { FixField.FIX_AggressorIndicator, false }, // BOOLEAN
        { FixField.FIX_AgreementCurrency, false }, // CURRENCY
        { FixField.FIX_AgreementDate, false }, // LOCALMKTDATE
        { FixField.FIX_AgreementDesc, false }, // STRING
        { FixField.FIX_AgreementID, false }, // STRING
        { FixField.FIX_AllocAccount, false }, // STRING
        { FixField.FIX_AllocAccountType, true }, // INT
        { FixField.FIX_AllocAccruedInterestAmt, true }, // AMT
        { FixField.FIX_AllocAcctIDSource, true }, // INT
        { FixField.FIX_AllocAvgPx, true }, // PRICE
        { FixField.FIX_AllocCancReplaceReason, true }, // INT
        { FixField.FIX_AllocClearingFeeIndicator, false }, // STRING
        { FixField.FIX_AllocCustomerCapacity, false }, // STRING
        { FixField.FIX_AllocHandlInst, true }, // INT
        { FixField.FIX_AllocID, false }, // STRING
        { FixField.FIX_AllocInterestAtMaturity, true }, // AMT
        { FixField.FIX_AllocIntermedReqType, true }, // INT
        { FixField.FIX_AllocLinkID, false }, // STRING
        { FixField.FIX_AllocLinkType, true }, // INT
        { FixField.FIX_AllocMethod, true }, // INT
        { FixField.FIX_AllocNetMoney, true }, // AMT
        { FixField.FIX_AllocNoOrdersType, true }, // INT
        { FixField.FIX_AllocPositionEffect, false }, // CHAR
        { FixField.FIX_AllocPrice, true }, // PRICE
        { FixField.FIX_AllocQty, true }, // QTY
        { FixField.FIX_AllocRejCode, true }, // INT
        { FixField.FIX_AllocReportID, false }, // STRING
        { FixField.FIX_AllocReportRefID, false }, // STRING
        { FixField.FIX_AllocReportType, true }, // INT
        { FixField.FIX_AllocSettlCurrAmt, true }, // AMT
        { FixField.FIX_AllocSettlCurrency, false }, // CURRENCY
        { FixField.FIX_AllocSettlInstType, true }, // INT
        { FixField.FIX_AllocStatus, true }, // INT
        { FixField.FIX_AllocText, false }, // STRING
        { FixField.FIX_AllocTransType, false }, // CHAR
        { FixField.FIX_AllocType, true }, // INT
        { FixField.FIX_AllowableOneSidednessCurr, false }, // CURRENCY
        { FixField.FIX_AllowableOneSidednessPct, true }, // PERCENTAGE
        { FixField.FIX_AllowableOneSidednessValue, true }, // AMT
        { FixField.FIX_AltMDSourceID, false }, // STRING
        { FixField.FIX_ApplBegSeqNum, true }, // SEQNUM
        { FixField.FIX_ApplEndSeqNum, true }, // SEQNUM
        { FixField.FIX_ApplExtID, true }, // INT
        { FixField.FIX_ApplID, false }, // STRING
        { FixField.FIX_ApplLastSeqNum, true }, // SEQNUM
        { FixField.FIX_ApplNewSeqNum, true }, // SEQNUM
        { FixField.FIX_ApplQueueAction, true }, // INT
        { FixField.FIX_ApplQueueDepth, true }, // INT
        { FixField.FIX_ApplQueueMax, true }, // INT
        { FixField.FIX_ApplQueueResolution, true }, // INT
        { FixField.FIX_ApplReportID, false }, // STRING
        { FixField.FIX_ApplReportType, true }, // INT
        { FixField.FIX_ApplReqID, false }, // STRING
        { FixField.FIX_ApplReqType, true }, // INT
        { FixField.FIX_ApplResendFlag, false }, // BOOLEAN
        { FixField.FIX_ApplResponseError, true }, // INT
        { FixField.FIX_ApplResponseID, false }, // STRING
        { FixField.FIX_ApplResponseType, true }, // INT
        { FixField.FIX_ApplSeqNum, true }, // SEQNUM
        { FixField.FIX_ApplTotalMessageCount, true }, // INT
        { FixField.FIX_ApplVerID, false }, // STRING
        { FixField.FIX_AsOfIndicator, false }, // CHAR
        { FixField.FIX_AsgnRptID, false }, // STRING
        { FixField.FIX_AssignmentMethod, false }, // CHAR
        { FixField.FIX_AssignmentUnit, true }, // QTY
        { FixField.FIX_AttachmentPoint, true }, // PERCENTAGE
        { FixField.FIX_AutoAcceptIndicator, false }, // BOOLEAN
        { FixField.FIX_AvgParPx, true }, // PRICE
        { FixField.FIX_AvgPx, true }, // PRICE
        { FixField.FIX_AvgPxIndicator, true }, // INT
        { FixField.FIX_AvgPxPrecision, true }, // INT
        { FixField.FIX_BasisFeatureDate, false }, // LOCALMKTDATE
        { FixField.FIX_BasisFeaturePrice, true }, // PRICE
        { FixField.FIX_BasisPxType, false }, // CHAR
        { FixField.FIX_BeginSeqNo, true }, // SEQNUM
        { FixField.FIX_BeginString, false }, // STRING
        { FixField.FIX_BenchmarkCurveCurrency, false }, // CURRENCY
        { FixField.FIX_BenchmarkCurveName, false }, // STRING
        { FixField.FIX_BenchmarkCurvePoint, false }, // STRING
        { FixField.FIX_BenchmarkPrice, true }, // PRICE
        { FixField.FIX_BenchmarkPriceType, true }, // INT
        { FixField.FIX_BenchmarkSecurityID, false }, // STRING
        { FixField.FIX_BenchmarkSecurityIDSource, false }, // STRING
        { FixField.FIX_BidDescriptor, false }, // STRING
        { FixField.FIX_BidDescriptorType, true }, // INT
        { FixField.FIX_BidForwardPoints, true }, // PRICEOFFSET
        { FixField.FIX_BidForwardPoints2, true }, // PRICEOFFSET
        { FixField.FIX_BidID, false }, // STRING
        { FixField.FIX_BidPx, true }, // PRICE
        { FixField.FIX_BidRequestTransType, false }, // CHAR
        { FixField.FIX_BidSize, true }, // QTY
        { FixField.FIX_BidSpotRate, true }, // PRICE
        { FixField.FIX_BidSwapPoints, true }, // PRICEOFFSET
        { FixField.FIX_BidTradeType, false }, // CHAR
        { FixField.FIX_BidType, true }, // INT
        { FixField.FIX_BidYield, true }, // PERCENTAGE
        { FixField.FIX_BodyLength, true }, // LENGTH
        { FixField.FIX_BookingRefID, false }, // STRING
        { FixField.FIX_BookingType, true }, // INT
        { FixField.FIX_BookingUnit, false }, // CHAR
        { FixField.FIX_BusinessRejectReason, true }, // INT
        { FixField.FIX_BusinessRejectRefID, false }, // STRING
        { FixField.FIX_BuyVolume, true }, // QTY
        { FixField.FIX_CFICode, false }, // STRING
        { FixField.FIX_CPProgram, true }, // INT
        { FixField.FIX_CPRegType, false }, // STRING
        { FixField.FIX_CalculatedCcyLastQty, true }, // QTY
        { FixField.FIX_CancellationRights, false }, // CHAR
        { FixField.FIX_CapPrice, true }, // PRICE
        { FixField.FIX_CardExpDate, false }, // LOCALMKTDATE
        { FixField.FIX_CardHolderName, false }, // STRING
        { FixField.FIX_CardIssNum, false }, // STRING
        { FixField.FIX_CardNumber, false }, // STRING
        { FixField.FIX_CardStartDate, false }, // LOCALMKTDATE
        { FixField.FIX_CashDistribAgentAcctName, false }, // STRING
        { FixField.FIX_CashDistribAgentAcctNumber, false }, // STRING
        { FixField.FIX_CashDistribAgentCode, false }, // STRING
        { FixField.FIX_CashDistribAgentName, false }, // STRING
        { FixField.FIX_CashDistribCurr, false }, // CURRENCY
        { FixField.FIX_CashDistribPayRef, false }, // STRING
        { FixField.FIX_CashMargin, false }, // CHAR
        { FixField.FIX_CashOrderQty, true }, // QTY
        { FixField.FIX_CashOutstanding, true }, // AMT
        { FixField.FIX_CcyAmt, true }, // AMT
        { FixField.FIX_CheckSum, false }, // STRING
        { FixField.FIX_ClOrdID, false }, // STRING
        { FixField.FIX_ClOrdLinkID, false }, // STRING
        { FixField.FIX_ClearingBusinessDate, false }, // LOCALMKTDATE
        { FixField.FIX_ClearingFeeIndicator, false }, // STRING
        { FixField.FIX_ClearingInstruction, true }, // INT
        { FixField.FIX_ClientBidID, false }, // STRING
        { FixField.FIX_CollAction, true }, // INT
        { FixField.FIX_CollApplType, true }, // INT
        { FixField.FIX_CollAsgnID, false }, // STRING
        { FixField.FIX_CollAsgnReason, true }, // INT
        { FixField.FIX_CollAsgnRefID, false }, // STRING
        { FixField.FIX_CollAsgnRejectReason, true }, // INT
        { FixField.FIX_CollAsgnRespType, true }, // INT
        { FixField.FIX_CollAsgnTransType, true }, // INT
        { FixField.FIX_CollInquiryID, false }, // STRING
        { FixField.FIX_CollInquiryQualifier, true }, // INT
        { FixField.FIX_CollInquiryResult, true }, // INT
        { FixField.FIX_CollInquiryStatus, true }, // INT
        { FixField.FIX_CollReqID, false }, // STRING
        { FixField.FIX_CollRespID, false }, // STRING
        { FixField.FIX_CollRptID, false }, // STRING
        { FixField.FIX_CollStatus, true }, // INT
        { FixField.FIX_CommCurrency, false }, // CURRENCY
        { FixField.FIX_CommType, false }, // CHAR
        { FixField.FIX_Commission, true }, // AMT
        { FixField.FIX_ComplexEventCondition, true }, // INT
        { FixField.FIX_ComplexEventEndDate, false }, // UTCTIMESTAMP
        { FixField.FIX_ComplexEventEndTime, false }, // UTCTIMEONLY
        { FixField.FIX_ComplexEventPrice, true }, // PRICE
        { FixField.FIX_ComplexEventPriceBoundaryMethod, true }, // INT
        { FixField.FIX_ComplexEventPriceBoundaryPrecision, true }, // PERCENTAGE
        { FixField.FIX_ComplexEventPriceTimeType, true }, // INT
        { FixField.FIX_ComplexEventStartDate, false }, // UTCTIMESTAMP
        { FixField.FIX_ComplexEventStartTime, false }, // UTCTIMEONLY
        { FixField.FIX_ComplexEventType, true }, // INT
        { FixField.FIX_ComplexOptPayoutAmount, true }, // AMT
        { FixField.FIX_ComplianceID, false }, // STRING
        { FixField.FIX_Concession, true }, // AMT
        { FixField.FIX_ConfirmID, false }, // STRING
        { FixField.FIX_ConfirmRefID, false }, // STRING
        { FixField.FIX_ConfirmRejReason, true }, // INT
        { FixField.FIX_ConfirmReqID, false }, // STRING
        { FixField.FIX_ConfirmStatus, true }, // INT
        { FixField.FIX_ConfirmTransType, true }, // INT
        { FixField.FIX_ConfirmType, true }, // INT
        { FixField.FIX_ContAmtCurr, false }, // CURRENCY
        { FixField.FIX_ContAmtType, true }, // INT
        { FixField.FIX_ContAmtValue, true }, // FLOAT
        { FixField.FIX_ContIntRptID, false }, // STRING
        { FixField.FIX_ContingencyType, true }, // INT
        { FixField.FIX_ContraBroker, false }, // STRING
        { FixField.FIX_ContraLegRefID, false }, // STRING
        { FixField.FIX_ContraTradeQty, true }, // QTY
        { FixField.FIX_ContraTradeTime, false }, // UTCTIMESTAMP
        { FixField.FIX_ContraTrader, false }, // STRING
        { FixField.FIX_ContractMultiplier, true }, // FLOAT
        { FixField.FIX_ContractMultiplierUnit, true }, // INT
        { FixField.FIX_ContractSettlMonth, false }, // MONTHYEAR
        { FixField.FIX_ContraryInstructionIndicator, false }, // BOOLEAN
        { FixField.FIX_CopyMsgIndicator, false }, // BOOLEAN
        { FixField.FIX_CorporateAction, false }, // MULTIPLECHARVALUE
        { FixField.FIX_Country, false }, // COUNTRY
        { FixField.FIX_CountryOfIssue, false }, // COUNTRY
        { FixField.FIX_CouponPaymentDate, false }, // LOCALMKTDATE
        { FixField.FIX_CouponRate, true }, // PERCENTAGE
        { FixField.FIX_CoveredOrUncovered, true }, // INT
        { FixField.FIX_CreditRating, false }, // STRING
        { FixField.FIX_CrossID, false }, // STRING
        { FixField.FIX_CrossPercent, true }, // PERCENTAGE
        { FixField.FIX_CrossPrioritization, true }, // INT
        { FixField.FIX_CrossType, true }, // INT
        { FixField.FIX_CstmApplVerID, false }, // STRING
        { FixField.FIX_CumQty, true }, // QTY
        { FixField.FIX_Currency, false }, // CURRENCY
        { FixField.FIX_CurrencyRatio, true }, // FLOAT
        { FixField.FIX_CustDirectedOrder, false }, // BOOLEAN
        { FixField.FIX_CustOrderCapacity, true }, // INT
        { FixField.FIX_CustOrderHandlingInst, false }, // MULTIPLESTRINGVALUE
        { FixField.FIX_CxlQty, true }, // QTY
        { FixField.FIX_CxlRejReason, true }, // INT
        { FixField.FIX_CxlRejResponseTo, false }, // CHAR
        { FixField.FIX_DKReason, false }, // CHAR
        { FixField.FIX_DateOfBirth, false }, // LOCALMKTDATE
        { FixField.FIX_DatedDate, false }, // LOCALMKTDATE
        { FixField.FIX_DayAvgPx, true }, // PRICE
        { FixField.FIX_DayBookingInst, false }, // CHAR
        { FixField.FIX_DayCumQty, true }, // QTY
        { FixField.FIX_DayOrderQty, true }, // QTY
        { FixField.FIX_DealingCapacity, false }, // CHAR
        { FixField.FIX_DefBidSize, true }, // QTY
        { FixField.FIX_DefOfferSize, true }, // QTY
        { FixField.FIX_DefaultApplExtID, true }, // INT
        { FixField.FIX_DefaultApplVerID, false }, // STRING
        { FixField.FIX_DefaultCstmApplVerID, false }, // STRING
        { FixField.FIX_DefaultVerIndicator, false }, // BOOLEAN
        { FixField.FIX_DeleteReason, false }, // CHAR
        { FixField.FIX_DeliverToCompID, false }, // STRING
        { FixField.FIX_DeliverToLocationID, false }, // STRING
        { FixField.FIX_DeliverToSubID, false }, // STRING
        { FixField.FIX_DeliveryDate, false }, // LOCALMKTDATE
        { FixField.FIX_DeliveryForm, true }, // INT
        { FixField.FIX_DeliveryType, true }, // INT
        { FixField.FIX_DerivFlexProductEligibilityIndicator, false }, // BOOLEAN
        { FixField.FIX_DerivativeCFICode, false }, // STRING
        { FixField.FIX_DerivativeCapPrice, true }, // PRICE
        { FixField.FIX_DerivativeContractMultiplier, true }, // FLOAT
        { FixField.FIX_DerivativeContractMultiplierUnit, true }, // INT
        { FixField.FIX_DerivativeContractSettlMonth, false }, // MONTHYEAR
        { FixField.FIX_DerivativeCountryOfIssue, false }, // COUNTRY
        { FixField.FIX_DerivativeEncodedIssuer, false }, // DATA
        { FixField.FIX_DerivativeEncodedIssuerLen, true }, // LENGTH
        { FixField.FIX_DerivativeEncodedSecurityDesc, false }, // DATA
        { FixField.FIX_DerivativeEncodedSecurityDescLen, true }, // LENGTH
        { FixField.FIX_DerivativeEventDate, false }, // LOCALMKTDATE
        { FixField.FIX_DerivativeEventPx, true }, // PRICE
        { FixField.FIX_DerivativeEventText, false }, // STRING
        { FixField.FIX_DerivativeEventTime, false }, // UTCTIMESTAMP
        { FixField.FIX_DerivativeEventType, true }, // INT
        { FixField.FIX_DerivativeExerciseStyle, false }, // CHAR
        { FixField.FIX_DerivativeFloorPrice, true }, // PRICE
        { FixField.FIX_DerivativeFlowScheduleType, true }, // INT
        { FixField.FIX_DerivativeInstrAttribType, true }, // INT
        { FixField.FIX_DerivativeInstrAttribValue, false }, // STRING
        { FixField.FIX_DerivativeInstrRegistry, false }, // STRING
        { FixField.FIX_DerivativeInstrmtAssignmentMethod, false }, // CHAR
        { FixField.FIX_DerivativeInstrumentPartyID, false }, // STRING
        { FixField.FIX_DerivativeInstrumentPartyIDSource, false }, // STRING
        { FixField.FIX_DerivativeInstrumentPartyRole, true }, // INT
        { FixField.FIX_DerivativeInstrumentPartySubID, false }, // STRING
        { FixField.FIX_DerivativeInstrumentPartySubIDType, true }, // INT
        { FixField.FIX_DerivativeIssueDate, false }, // LOCALMKTDATE
        { FixField.FIX_DerivativeIssuer, false }, // STRING
        { FixField.FIX_DerivativeListMethod, true }, // INT
        { FixField.FIX_DerivativeLocaleOfIssue, false }, // STRING
        { FixField.FIX_DerivativeMaturityDate, false }, // LOCALMKTDATE
        { FixField.FIX_DerivativeMaturityMonthYear, false }, // MONTHYEAR
        { FixField.FIX_DerivativeMaturityTime, false }, // TZTIMEONLY
        { FixField.FIX_DerivativeMinPriceIncrement, true }, // FLOAT
        { FixField.FIX_DerivativeMinPriceIncrementAmount, true }, // AMT
        { FixField.FIX_DerivativeNTPositionLimit, true }, // INT
        { FixField.FIX_DerivativeOptAttribute, false }, // CHAR
        { FixField.FIX_DerivativeOptPayAmount, true }, // AMT
        { FixField.FIX_DerivativePositionLimit, true }, // INT
        { FixField.FIX_DerivativePriceQuoteMethod, false }, // STRING
        { FixField.FIX_DerivativePriceUnitOfMeasure, false }, // STRING
        { FixField.FIX_DerivativePriceUnitOfMeasureQty, true }, // QTY
        { FixField.FIX_DerivativeProduct, true }, // INT
        { FixField.FIX_DerivativeProductComplex, false }, // STRING
        { FixField.FIX_DerivativePutOrCall, true }, // INT
        { FixField.FIX_DerivativeSecurityAltID, false }, // STRING
        { FixField.FIX_DerivativeSecurityAltIDSource, false }, // STRING
        { FixField.FIX_DerivativeSecurityDesc, false }, // STRING
        { FixField.FIX_DerivativeSecurityExchange, false }, // EXCHANGE
        { FixField.FIX_DerivativeSecurityGroup, false }, // STRING
        { FixField.FIX_DerivativeSecurityID, false }, // STRING
        { FixField.FIX_DerivativeSecurityIDSource, false }, // STRING
        { FixField.FIX_DerivativeSecurityStatus, false }, // STRING
        { FixField.FIX_DerivativeSecuritySubType, false }, // STRING
        { FixField.FIX_DerivativeSecurityType, false }, // STRING
        { FixField.FIX_DerivativeSecurityXML, false }, // DATA
        { FixField.FIX_DerivativeSecurityXMLLen, true }, // LENGTH
        { FixField.FIX_DerivativeSecurityXMLSchema, false }, // STRING
        { FixField.FIX_DerivativeSettlMethod, false }, // CHAR
        { FixField.FIX_DerivativeSettleOnOpenFlag, false }, // STRING
        { FixField.FIX_DerivativeStateOrProvinceOfIssue, false }, // STRING
        { FixField.FIX_DerivativeStrikeCurrency, false }, // CURRENCY
        { FixField.FIX_DerivativeStrikeMultiplier, true }, // FLOAT
        { FixField.FIX_DerivativeStrikePrice, true }, // PRICE
        { FixField.FIX_DerivativeStrikeValue, true }, // FLOAT
        { FixField.FIX_DerivativeSymbol, false }, // STRING
        { FixField.FIX_DerivativeSymbolSfx, false }, // STRING
        { FixField.FIX_DerivativeTimeUnit, false }, // STRING
        { FixField.FIX_DerivativeUnitOfMeasure, false }, // STRING
        { FixField.FIX_DerivativeUnitOfMeasureQty, true }, // QTY
        { FixField.FIX_DerivativeValuationMethod, false }, // STRING
        { FixField.FIX_Designation, false }, // STRING
        { FixField.FIX_DeskID, false }, // STRING
        { FixField.FIX_DeskOrderHandlingInst, false }, // MULTIPLESTRINGVALUE
        { FixField.FIX_DeskType, false }, // STRING
        { FixField.FIX_DeskTypeSource, true }, // INT
        { FixField.FIX_DetachmentPoint, true }, // PERCENTAGE
        { FixField.FIX_DiscretionInst, false }, // CHAR
        { FixField.FIX_DiscretionLimitType, true }, // INT
        { FixField.FIX_DiscretionMoveType, true }, // INT
        { FixField.FIX_DiscretionOffsetType, true }, // INT
        { FixField.FIX_DiscretionOffsetValue, true }, // FLOAT
        { FixField.FIX_DiscretionPrice, true }, // PRICE
        { FixField.FIX_DiscretionRoundDirection, true }, // INT
        { FixField.FIX_DiscretionScope, true }, // INT
        { FixField.FIX_DisplayHighQty, true }, // QTY
        { FixField.FIX_DisplayLowQty, true }, // QTY
        { FixField.FIX_DisplayMethod, false }, // CHAR
        { FixField.FIX_DisplayMinIncr, true }, // QTY
        { FixField.FIX_DisplayQty, true }, // QTY
        { FixField.FIX_DisplayWhen, false }, // CHAR
        { FixField.FIX_DistribPaymentMethod, true }, // INT
        { FixField.FIX_DistribPercentage, true }, // PERCENTAGE
        { FixField.FIX_DividendYield, true }, // PERCENTAGE
        { FixField.FIX_DlvyInstType, false }, // CHAR
        { FixField.FIX_DueToRelated, false }, // BOOLEAN
        { FixField.FIX_EFPTrackingError, true }, // PERCENTAGE
        { FixField.FIX_EffectiveTime, false }, // UTCTIMESTAMP
        { FixField.FIX_EmailThreadID, false }, // STRING
        { FixField.FIX_EmailType, false }, // CHAR
        { FixField.FIX_EncodedAllocText, false }, // DATA
        { FixField.FIX_EncodedAllocTextLen, true }, // LENGTH
        { FixField.FIX_EncodedHeadline, false }, // DATA
        { FixField.FIX_EncodedHeadlineLen, true }, // LENGTH
        { FixField.FIX_EncodedIssuer, false }, // DATA
        { FixField.FIX_EncodedIssuerLen, true }, // LENGTH
        { FixField.FIX_EncodedLegIssuer, false }, // DATA
        { FixField.FIX_EncodedLegIssuerLen, true }, // LENGTH
        { FixField.FIX_EncodedLegSecurityDesc, false }, // DATA
        { FixField.FIX_EncodedLegSecurityDescLen, true }, // LENGTH
        { FixField.FIX_EncodedListExecInst, false }, // DATA
        { FixField.FIX_EncodedListExecInstLen, true }, // LENGTH
        { FixField.FIX_EncodedListStatusText, false }, // DATA
        { FixField.FIX_EncodedListStatusTextLen, true }, // LENGTH
        { FixField.FIX_EncodedMktSegmDesc, false }, // DATA
        { FixField.FIX_EncodedMktSegmDescLen, true }, // LENGTH
        { FixField.FIX_EncodedSecurityDesc, false }, // DATA
        { FixField.FIX_EncodedSecurityDescLen, true }, // LENGTH
        { FixField.FIX_EncodedSecurityListDesc, false }, // DATA
        { FixField.FIX_EncodedSecurityListDescLen, true }, // LENGTH
        { FixField.FIX_EncodedSubject, false }, // DATA
        { FixField.FIX_EncodedSubjectLen, true }, // LENGTH
        { FixField.FIX_EncodedText, false }, // DATA
        { FixField.FIX_EncodedTextLen, true }, // LENGTH
        { FixField.FIX_EncodedUnderlyingIssuer, false }, // DATA
        { FixField.FIX_EncodedUnderlyingIssuerLen, true }, // LENGTH
        { FixField.FIX_EncodedUnderlyingSecurityDesc, false }, // DATA
        { FixField.FIX_EncodedUnderlyingSecurityDescLen, true }, // LENGTH
        { FixField.FIX_EncryptMethod, true }, // INT
        { FixField.FIX_EncryptedNewPassword, false }, // DATA
        { FixField.FIX_EncryptedNewPasswordLen, true }, // LENGTH
        { FixField.FIX_EncryptedPassword, false }, // DATA
        { FixField.FIX_EncryptedPasswordLen, true }, // LENGTH
        { FixField.FIX_EncryptedPasswordMethod, true }, // INT
        { FixField.FIX_EndAccruedInterestAmt, true }, // AMT
        { FixField.FIX_EndCash, true }, // AMT
        { FixField.FIX_EndDate, false }, // LOCALMKTDATE
        { FixField.FIX_EndMaturityMonthYear, false }, // MONTHYEAR
        { FixField.FIX_EndSeqNo, true }, // SEQNUM
        { FixField.FIX_EndStrikePxRange, true }, // PRICE
        { FixField.FIX_EndTickPriceRange, true }, // PRICE
        { FixField.FIX_EventDate, false }, // LOCALMKTDATE
        { FixField.FIX_EventPx, true }, // PRICE
        { FixField.FIX_EventText, false }, // STRING
        { FixField.FIX_EventTime, false }, // UTCTIMESTAMP
        { FixField.FIX_EventType, true }, // INT
        { FixField.FIX_ExDate, false }, // LOCALMKTDATE
        { FixField.FIX_ExDestination, false }, // EXCHANGE
        { FixField.FIX_ExDestinationIDSource, false }, // CHAR
        { FixField.FIX_ExchangeForPhysical, false }, // BOOLEAN
        { FixField.FIX_ExchangeRule, false }, // STRING
        { FixField.FIX_ExchangeSpecialInstructions, false }, // STRING
        { FixField.FIX_ExecAckStatus, false }, // CHAR
        { FixField.FIX_ExecID, false }, // STRING
        { FixField.FIX_ExecInst, false }, // MULTIPLECHARVALUE
        { FixField.FIX_ExecInstValue, false }, // CHAR
        { FixField.FIX_ExecPriceAdjustment, true }, // FLOAT
        { FixField.FIX_ExecPriceType, false }, // CHAR
        { FixField.FIX_ExecRefID, false }, // STRING
        { FixField.FIX_ExecRestatementReason, true }, // INT
        { FixField.FIX_ExecType, false }, // CHAR
        { FixField.FIX_ExecValuationPoint, false }, // UTCTIMESTAMP
        { FixField.FIX_ExerciseMethod, false }, // CHAR
        { FixField.FIX_ExerciseStyle, true }, // INT
        { FixField.FIX_ExpQty, true }, // QTY
        { FixField.FIX_ExpirationCycle, true }, // INT
        { FixField.FIX_ExpirationQtyType, true }, // INT
        { FixField.FIX_ExpireDate, false }, // LOCALMKTDATE
        { FixField.FIX_ExpireTime, false }, // UTCTIMESTAMP
        { FixField.FIX_Factor, true }, // FLOAT
        { FixField.FIX_FairValue, true }, // AMT
        { FixField.FIX_FeeMultiplier, true }, // FLOAT
        { FixField.FIX_FillExecID, false }, // STRING
        { FixField.FIX_FillLiquidityInd, true }, // INT
        { FixField.FIX_FillPx, true }, // PRICE
        { FixField.FIX_FillQty, true }, // QTY
        { FixField.FIX_FinancialStatus, false }, // MULTIPLECHARVALUE
        { FixField.FIX_FirmTradeID, false }, // STRING
        { FixField.FIX_FirstPx, true }, // PRICE
        { FixField.FIX_FlexProductEligibilityIndicator, false }, // BOOLEAN
        { FixField.FIX_FlexibleIndicator, false }, // BOOLEAN
        { FixField.FIX_FloorPrice, true }, // PRICE
        { FixField.FIX_FlowScheduleType, true }, // INT
        { FixField.FIX_ForexReq, false }, // BOOLEAN
        { FixField.FIX_FundRenewWaiv, false }, // CHAR
        { FixField.FIX_GTBookingInst, true }, // INT
        { FixField.FIX_GapFillFlag, false }, // BOOLEAN
        { FixField.FIX_GrossTradeAmt, true }, // AMT
        { FixField.FIX_HaltReason, true }, // INT
        { FixField.FIX_HandlInst, false }, // CHAR
        { FixField.FIX_Headline, false }, // STRING
        { FixField.FIX_HeartBtInt, true }, // INT
        { FixField.FIX_HighLimitPrice, true }, // PRICE
        { FixField.FIX_HighPx, true }, // PRICE
        { FixField.FIX_HopCompID, false }, // STRING
        { FixField.FIX_HopRefID, true }, // SEQNUM
        { FixField.FIX_HopSendingTime, false }, // UTCTIMESTAMP
        { FixField.FIX_HostCrossID, false }, // STRING
        { FixField.FIX_IOIID, false }, // STRING
        { FixField.FIX_IOINaturalFlag, false }, // BOOLEAN
        { FixField.FIX_IOIQltyInd, false }, // CHAR
        { FixField.FIX_IOIQty, false }, // STRING
        { FixField.FIX_IOIQualifier, false }, // CHAR
        { FixField.FIX_IOIRefID, false }, // STRING
        { FixField.FIX_IOITransType, false }, // CHAR
        { FixField.FIX_ImpliedMarketIndicator, true }, // INT
        { FixField.FIX_InViewOfCommon, false }, // BOOLEAN
        { FixField.FIX_IncTaxInd, true }, // INT
        { FixField.FIX_IndividualAllocID, false }, // STRING
        { FixField.FIX_IndividualAllocRejCode, true }, // INT
        { FixField.FIX_IndividualAllocType, true }, // INT
        { FixField.FIX_InputSource, false }, // STRING
        { FixField.FIX_InstrAttribType, true }, // INT
        { FixField.FIX_InstrAttribValue, false }, // STRING
        { FixField.FIX_InstrRegistry, false }, // STRING
        { FixField.FIX_InstrmtAssignmentMethod, false }, // CHAR
        { FixField.FIX_InstrumentPartyID, false }, // STRING
        { FixField.FIX_InstrumentPartyIDSource, false }, // CHAR
        { FixField.FIX_InstrumentPartyRole, true }, // INT
        { FixField.FIX_InstrumentPartySubID, false }, // STRING
        { FixField.FIX_InstrumentPartySubIDType, true }, // INT
        { FixField.FIX_InterestAccrualDate, false }, // LOCALMKTDATE
        { FixField.FIX_InterestAtMaturity, true }, // AMT
        { FixField.FIX_InvestorCountryOfResidence, false }, // COUNTRY
        { FixField.FIX_IssueDate, false }, // LOCALMKTDATE
        { FixField.FIX_Issuer, false }, // STRING
        { FixField.FIX_LanguageCode, false }, // LANGUAGE
        { FixField.FIX_LastCapacity, false }, // CHAR
        { FixField.FIX_LastForwardPoints, true }, // PRICEOFFSET
        { FixField.FIX_LastForwardPoints2, true }, // PRICEOFFSET
        { FixField.FIX_LastFragment, false }, // BOOLEAN
        { FixField.FIX_LastLiquidityInd, false }, // CHAR
        { FixField.FIX_LastMkt, false }, // EXCHANGE
        { FixField.FIX_LastMsgSeqNumProcessed, true }, // SEQNUM
        { FixField.FIX_LastNetworkResponseID, false }, // STRING
        { FixField.FIX_LastParPx, true }, // PRICE
        { FixField.FIX_LastPx, true }, // PRICE
        { FixField.FIX_LastQty, true }, // QTY
        { FixField.FIX_LastRptRequested, false }, // BOOLEAN
        { FixField.FIX_LastSpotRate, true }, // PRICE
        { FixField.FIX_LastSwapPoints, true }, // PRICEOFFSET
        { FixField.FIX_LastUpdateTime, false }, // UTCTIMESTAMP
        { FixField.FIX_LateIndicator, false }, // BOOLEAN
        { FixField.FIX_LeavesQty, true }, // QTY
        { FixField.FIX_LegAllocAccount, false }, // STRING
        { FixField.FIX_LegAllocAcctIDSource, false }, // STRING
        { FixField.FIX_LegAllocID, false }, // STRING
        { FixField.FIX_LegAllocQty, true }, // QTY
        { FixField.FIX_LegAllocSettlCurrency, false }, // CURRENCY
        { FixField.FIX_LegBenchmarkCurveCurrency, false }, // CURRENCY
        { FixField.FIX_LegBenchmarkCurveName, false }, // STRING
        { FixField.FIX_LegBenchmarkCurvePoint, false }, // STRING
        { FixField.FIX_LegBenchmarkPrice, true }, // PRICE
        { FixField.FIX_LegBenchmarkPriceType, true }, // INT
        { FixField.FIX_LegBidForwardPoints, true }, // PRICEOFFSET
        { FixField.FIX_LegBidPx, true }, // PRICE
        { FixField.FIX_LegCFICode, false }, // STRING
        { FixField.FIX_LegCalculatedCcyLastQty, true }, // QTY
        { FixField.FIX_LegContractMultiplier, true }, // FLOAT
        { FixField.FIX_LegContractMultiplierUnit, true }, // INT
        { FixField.FIX_LegContractSettlMonth, false }, // MONTHYEAR
        { FixField.FIX_LegCountryOfIssue, false }, // COUNTRY
        { FixField.FIX_LegCouponPaymentDate, false }, // LOCALMKTDATE
        { FixField.FIX_LegCouponRate, true }, // PERCENTAGE
        { FixField.FIX_LegCoveredOrUncovered, true }, // INT
        { FixField.FIX_LegCreditRating, false }, // STRING
        { FixField.FIX_LegCurrency, false }, // CURRENCY
        { FixField.FIX_LegCurrencyRatio, true }, // FLOAT
        { FixField.FIX_LegDatedDate, false }, // LOCALMKTDATE
        { FixField.FIX_LegDividendYield, true }, // PERCENTAGE
        { FixField.FIX_LegExecInst, false }, // MULTIPLECHARVALUE
        { FixField.FIX_LegExerciseStyle, true }, // INT
        { FixField.FIX_LegFactor, true }, // FLOAT
        { FixField.FIX_LegFlowScheduleType, true }, // INT
        { FixField.FIX_LegGrossTradeAmt, true }, // AMT
        { FixField.FIX_LegIOIQty, false }, // STRING
        { FixField.FIX_LegIndividualAllocID, false }, // STRING
        { FixField.FIX_LegInstrRegistry, false }, // STRING
        { FixField.FIX_LegInterestAccrualDate, false }, // LOCALMKTDATE
        { FixField.FIX_LegIssueDate, false }, // LOCALMKTDATE
        { FixField.FIX_LegIssuer, false }, // STRING
        { FixField.FIX_LegLastForwardPoints, true }, // PRICEOFFSET
        { FixField.FIX_LegLastPx, true }, // PRICE
        { FixField.FIX_LegLastQty, true }, // QTY
        { FixField.FIX_LegLocaleOfIssue, false }, // STRING
        { FixField.FIX_LegMaturityDate, false }, // LOCALMKTDATE
        { FixField.FIX_LegMaturityMonthYear, false }, // MONTHYEAR
        { FixField.FIX_LegMaturityTime, false }, // TZTIMEONLY
        { FixField.FIX_LegNumber, true }, // INT
        { FixField.FIX_LegOfferForwardPoints, true }, // PRICEOFFSET
        { FixField.FIX_LegOfferPx, true }, // PRICE
        { FixField.FIX_LegOptAttribute, false }, // CHAR
        { FixField.FIX_LegOptionRatio, true }, // FLOAT
        { FixField.FIX_LegOrderQty, true }, // QTY
        { FixField.FIX_LegPool, false }, // STRING
        { FixField.FIX_LegPositionEffect, false }, // CHAR
        { FixField.FIX_LegPrice, true }, // PRICE
        { FixField.FIX_LegPriceType, true }, // INT
        { FixField.FIX_LegPriceUnitOfMeasure, false }, // STRING
        { FixField.FIX_LegPriceUnitOfMeasureQty, true }, // QTY
        { FixField.FIX_LegProduct, true }, // INT
        { FixField.FIX_LegPutOrCall, true }, // INT
        { FixField.FIX_LegQty, true }, // QTY
        { FixField.FIX_LegRatioQty, true }, // FLOAT
        { FixField.FIX_LegRedemptionDate, false }, // LOCALMKTDATE
        { FixField.FIX_LegRefID, false }, // STRING
        { FixField.FIX_LegRepoCollateralSecurityType, true }, // INT
        { FixField.FIX_LegReportID, false }, // STRING
        { FixField.FIX_LegRepurchaseRate, true }, // PERCENTAGE
        { FixField.FIX_LegRepurchaseTerm, true }, // INT
        { FixField.FIX_LegSecurityAltID, false }, // STRING
        { FixField.FIX_LegSecurityAltIDSource, false }, // STRING
        { FixField.FIX_LegSecurityDesc, false }, // STRING
        { FixField.FIX_LegSecurityExchange, false }, // EXCHANGE
        { FixField.FIX_LegSecurityID, false }, // STRING
        { FixField.FIX_LegSecurityIDSource, false }, // STRING
        { FixField.FIX_LegSecuritySubType, false }, // STRING
        { FixField.FIX_LegSecurityType, false }, // STRING
        { FixField.FIX_LegSettlCurrency, false }, // CURRENCY
        { FixField.FIX_LegSettlDate, false }, // LOCALMKTDATE
        { FixField.FIX_LegSettlType, false }, // STRING
        { FixField.FIX_LegSide, false }, // CHAR
        { FixField.FIX_LegStateOrProvinceOfIssue, false }, // STRING
        { FixField.FIX_LegStipulationType, false }, // STRING
        { FixField.FIX_LegStipulationValue, false }, // STRING
        { FixField.FIX_LegStrikeCurrency, false }, // CURRENCY
        { FixField.FIX_LegStrikePrice, true }, // PRICE
        { FixField.FIX_LegSwapType, true }, // INT
        { FixField.FIX_LegSymbol, false }, // STRING
        { FixField.FIX_LegSymbolSfx, false }, // STRING
        { FixField.FIX_LegTimeUnit, false }, // STRING
        { FixField.FIX_LegUnitOfMeasure, false }, // STRING
        { FixField.FIX_LegUnitOfMeasureQty, true }, // QTY
        { FixField.FIX_LegVolatility, true }, // FLOAT
        { FixField.FIX_LegalConfirm, false }, // BOOLEAN
        { FixField.FIX_LiquidityIndType, true }, // INT
        { FixField.FIX_LiquidityNumSecurities, true }, // INT
        { FixField.FIX_LiquidityPctHigh, true }, // PERCENTAGE
        { FixField.FIX_LiquidityPctLow, true }, // PERCENTAGE
        { FixField.FIX_LiquidityValue, true }, // AMT
        { FixField.FIX_ListExecInst, false }, // STRING
        { FixField.FIX_ListExecInstType, false }, // CHAR
        { FixField.FIX_ListID, false }, // STRING
        { FixField.FIX_ListMethod, true }, // INT
        { FixField.FIX_ListName, false }, // STRING
        { FixField.FIX_ListOrderStatus, true }, // INT
        { FixField.FIX_ListRejectReason, true }, // INT
        { FixField.FIX_ListSeqNo, true }, // INT
        { FixField.FIX_ListStatusText, false }, // STRING
        { FixField.FIX_ListStatusType, true }, // INT
        { FixField.FIX_ListUpdateAction, false }, // CHAR
        { FixField.FIX_LocaleOfIssue, false }, // STRING
        { FixField.FIX_LocateReqd, false }, // BOOLEAN
        { FixField.FIX_LocationID, false }, // STRING
        { FixField.FIX_LongQty, true }, // QTY
        { FixField.FIX_LotType, false }, // CHAR
        { FixField.FIX_LowLimitPrice, true }, // PRICE
        { FixField.FIX_LowPx, true }, // PRICE
        { FixField.FIX_MDBookType, true }, // INT
        { FixField.FIX_MDEntryBuyer, false }, // STRING
        { FixField.FIX_MDEntryDate, false }, // UTCDATEONLY
        { FixField.FIX_MDEntryForwardPoints, true }, // PRICEOFFSET
        { FixField.FIX_MDEntryID, false }, // STRING
        { FixField.FIX_MDEntryOriginator, false }, // STRING
        { FixField.FIX_MDEntryPositionNo, true }, // INT
        { FixField.FIX_MDEntryPx, true }, // PRICE
        { FixField.FIX_MDEntryRefID, false }, // STRING
        { FixField.FIX_MDEntrySeller, false }, // STRING
        { FixField.FIX_MDEntrySize, true }, // QTY
        { FixField.FIX_MDEntrySpotRate, true }, // FLOAT
        { FixField.FIX_MDEntryTime, false }, // UTCTIMEONLY
        { FixField.FIX_MDEntryType, false }, // CHAR
        { FixField.FIX_MDFeedType, false }, // STRING
        { FixField.FIX_MDImplicitDelete, false }, // BOOLEAN
        { FixField.FIX_MDMkt, false }, // EXCHANGE
        { FixField.FIX_MDOriginType, true }, // INT
        { FixField.FIX_MDPriceLevel, true }, // INT
        { FixField.FIX_MDQuoteType, true }, // INT
        { FixField.FIX_MDReportID, true }, // INT
        { FixField.FIX_MDReqID, false }, // STRING
        { FixField.FIX_MDReqRejReason, false }, // CHAR
        { FixField.FIX_MDSecSize, true }, // QTY
        { FixField.FIX_MDSecSizeType, true }, // INT
        { FixField.FIX_MDStreamID, false }, // STRING
        { FixField.FIX_MDSubBookType, true }, // INT
        { FixField.FIX_MDUpdateAction, false }, // CHAR
        { FixField.FIX_MDUpdateType, true }, // INT
        { FixField.FIX_MailingDtls, false }, // STRING
        { FixField.FIX_MailingInst, false }, // STRING
        { FixField.FIX_ManualOrderIndicator, false }, // BOOLEAN
        { FixField.FIX_MarginExcess, true }, // AMT
        { FixField.FIX_MarginRatio, true }, // PERCENTAGE
        { FixField.FIX_MarketDepth, true }, // INT
        { FixField.FIX_MarketID, false }, // EXCHANGE
        { FixField.FIX_MarketReportID, false }, // STRING
        { FixField.FIX_MarketReqID, false }, // STRING
        { FixField.FIX_MarketSegmentDesc, false }, // STRING
        { FixField.FIX_MarketSegmentID, false }, // STRING
        { FixField.FIX_MarketUpdateAction, false }, // CHAR
        { FixField.FIX_MassActionRejectReason, true }, // INT
        { FixField.FIX_MassActionReportID, false }, // STRING
        { FixField.FIX_MassActionResponse, true }, // INT
        { FixField.FIX_MassActionScope, true }, // INT
        { FixField.FIX_MassActionType, true }, // INT
        { FixField.FIX_MassCancelRejectReason, true }, // INT
        { FixField.FIX_MassCancelRequestType, false }, // CHAR
        { FixField.FIX_MassCancelResponse, false }, // CHAR
        { FixField.FIX_MassStatusReqID, false }, // STRING
        { FixField.FIX_MassStatusReqType, true }, // INT
        { FixField.FIX_MatchAlgorithm, false }, // STRING
        { FixField.FIX_MatchIncrement, true }, // QTY
        { FixField.FIX_MatchStatus, false }, // CHAR
        { FixField.FIX_MatchType, false }, // STRING
        { FixField.FIX_MaturityDate, false }, // LOCALMKTDATE
        { FixField.FIX_MaturityMonthYear, false }, // MONTHYEAR
        { FixField.FIX_MaturityMonthYearFormat, true }, // INT
        { FixField.FIX_MaturityMonthYearIncrement, true }, // INT
        { FixField.FIX_MaturityMonthYearIncrementUnits, true }, // INT
        { FixField.FIX_MaturityNetMoney, true }, // AMT
        { FixField.FIX_MaturityRuleID, false }, // STRING
        { FixField.FIX_MaturityTime, false }, // TZTIMEONLY
        { FixField.FIX_MaxFloor, true }, // QTY
        { FixField.FIX_MaxMessageSize, true }, // LENGTH
        { FixField.FIX_MaxPriceLevels, true }, // INT
        { FixField.FIX_MaxPriceVariation, true }, // FLOAT
        { FixField.FIX_MaxShow, true }, // QTY
        { FixField.FIX_MaxTradeVol, true }, // QTY
        { FixField.FIX_MessageEncoding, false }, // STRING
        { FixField.FIX_MessageEventSource, false }, // STRING
        { FixField.FIX_MidPx, true }, // PRICE
        { FixField.FIX_MidYield, true }, // PERCENTAGE
        { FixField.FIX_MinBidSize, true }, // QTY
        { FixField.FIX_MinLotSize, true }, // QTY
        { FixField.FIX_MinOfferSize, true }, // QTY
        { FixField.FIX_MinPriceIncrement, true }, // FLOAT
        { FixField.FIX_MinPriceIncrementAmount, true }, // AMT
        { FixField.FIX_MinQty, true }, // QTY
        { FixField.FIX_MinTradeVol, true }, // QTY
        { FixField.FIX_MiscFeeAmt, true }, // AMT
        { FixField.FIX_MiscFeeBasis, true }, // INT
        { FixField.FIX_MiscFeeCurr, false }, // CURRENCY
        { FixField.FIX_MiscFeeType, false }, // STRING
        { FixField.FIX_MktBidPx, true }, // PRICE
        { FixField.FIX_MktOfferPx, true }, // PRICE
        { FixField.FIX_ModelType, true }, // INT
        { FixField.FIX_MoneyLaunderingStatus, false }, // CHAR
        { FixField.FIX_MsgDirection, false }, // CHAR
        { FixField.FIX_MsgSeqNum, true }, // SEQNUM
        { FixField.FIX_MsgType, false }, // STRING
        { FixField.FIX_MultiLegReportingType, false }, // CHAR
        { FixField.FIX_MultiLegRptTypeReq, true }, // INT
        { FixField.FIX_MultilegModel, true }, // INT
        { FixField.FIX_MultilegPriceMethod, true }, // INT
        { FixField.FIX_NTPositionLimit, true }, // INT
        { FixField.FIX_Nested2PartyID, false }, // STRING
        { FixField.FIX_Nested2PartyIDSource, false }, // CHAR
        { FixField.FIX_Nested2PartyRole, true }, // INT
        { FixField.FIX_Nested2PartySubID, false }, // STRING
        { FixField.FIX_Nested2PartySubIDType, true }, // INT
        { FixField.FIX_Nested3PartyID, false }, // STRING
        { FixField.FIX_Nested3PartyIDSource, false }, // CHAR
        { FixField.FIX_Nested3PartyRole, true }, // INT
        { FixField.FIX_Nested3PartySubID, false }, // STRING
        { FixField.FIX_Nested3PartySubIDType, true }, // INT
        { FixField.FIX_Nested4PartyID, false }, // STRING
        { FixField.FIX_Nested4PartyIDSource, false }, // CHAR
        { FixField.FIX_Nested4PartyRole, true }, // INT
        { FixField.FIX_Nested4PartySubID, false }, // STRING
        { FixField.FIX_Nested4PartySubIDType, true }, // INT
        { FixField.FIX_NestedInstrAttribType, true }, // INT
        { FixField.FIX_NestedInstrAttribValue, false }, // STRING
        { FixField.FIX_NestedPartyID, false }, // STRING
        { FixField.FIX_NestedPartyIDSource, false }, // CHAR
        { FixField.FIX_NestedPartyRole, true }, // INT
        { FixField.FIX_NestedPartySubID, false }, // STRING
        { FixField.FIX_NestedPartySubIDType, true }, // INT
        { FixField.FIX_NetChgPrevDay, true }, // PRICEOFFSET
        { FixField.FIX_NetGrossInd, true }, // INT
        { FixField.FIX_NetMoney, true }, // AMT
        { FixField.FIX_NetworkRequestID, false }, // STRING
        { FixField.FIX_NetworkRequestType, true }, // INT
        { FixField.FIX_NetworkResponseID, false }, // STRING
        { FixField.FIX_NetworkStatusResponseType, true }, // INT
        { FixField.FIX_NewPassword, false }, // STRING
        { FixField.FIX_NewSeqNo, true }, // SEQNUM
        { FixField.FIX_NewsCategory, true }, // INT
        { FixField.FIX_NewsID, false }, // STRING
        { FixField.FIX_NewsRefID, false }, // STRING
        { FixField.FIX_NewsRefType, true }, // INT
        { FixField.FIX_NextExpectedMsgSeqNum, true }, // SEQNUM
        { FixField.FIX_NoAffectedOrders, true }, // NUMINGROUP
        { FixField.FIX_NoAllocs, true }, // NUMINGROUP
        { FixField.FIX_NoAltMDSource, true }, // NUMINGROUP
        { FixField.FIX_NoApplIDs, true }, // NUMINGROUP
        { FixField.FIX_NoAsgnReqs, true }, // NUMINGROUP
        { FixField.FIX_NoBidComponents, true }, // NUMINGROUP
        { FixField.FIX_NoBidDescriptors, true }, // NUMINGROUP
        { FixField.FIX_NoCapacities, true }, // NUMINGROUP
        { FixField.FIX_NoClearingInstructions, true }, // NUMINGROUP
        { FixField.FIX_NoCollInquiryQualifier, true }, // NUMINGROUP
        { FixField.FIX_NoCompIDs, true }, // NUMINGROUP
        { FixField.FIX_NoComplexEventDates, true }, // NUMINGROUP
        { FixField.FIX_NoComplexEventTimes, true }, // NUMINGROUP
        { FixField.FIX_NoComplexEvents, true }, // NUMINGROUP
        { FixField.FIX_NoContAmts, true }, // NUMINGROUP
        { FixField.FIX_NoContraBrokers, true }, // NUMINGROUP
        { FixField.FIX_NoDates, true }, // INT
        { FixField.FIX_NoDerivativeEvents, true }, // NUMINGROUP
        { FixField.FIX_NoDerivativeInstrAttrib, true }, // NUMINGROUP
        { FixField.FIX_NoDerivativeInstrumentParties, true }, // NUMINGROUP
        { FixField.FIX_NoDerivativeInstrumentPartySubIDs, true }, // NUMINGROUP
        { FixField.FIX_NoDerivativeSecurityAltID, true }, // NUMINGROUP
        { FixField.FIX_NoDistribInsts, true }, // NUMINGROUP
        { FixField.FIX_NoDlvyInst, true }, // NUMINGROUP
        { FixField.FIX_NoEvents, true }, // NUMINGROUP
        { FixField.FIX_NoExecInstRules, true }, // NUMINGROUP
        { FixField.FIX_NoExecs, true }, // NUMINGROUP
        { FixField.FIX_NoExpiration, true }, // NUMINGROUP
        { FixField.FIX_NoFills, true }, // NUMINGROUP
        { FixField.FIX_NoHops, true }, // NUMINGROUP
        { FixField.FIX_NoIOIQualifiers, true }, // NUMINGROUP
        { FixField.FIX_NoInstrAttrib, true }, // NUMINGROUP
        { FixField.FIX_NoInstrumentParties, true }, // NUMINGROUP
        { FixField.FIX_NoInstrumentPartySubIDs, true }, // NUMINGROUP
        { FixField.FIX_NoLegAllocs, true }, // NUMINGROUP
        // Override: FIX50SP2.xml itself mistypes this one repeating-group counter as STRING
        // (verified against the raw spec file, line 8125) - every sibling No*SecurityAltID counter
        // (NoSecurityAltID, NoDerivativeSecurityAltID, NoUnderlyingSecurityAltID,
        // NoUnderlyingLegSecurityAltID) is NUMINGROUP, and FIX convention requires every NoXXX
        // repeating-group counter to be numeric. Gitar review finding on PR #117.
        { FixField.FIX_NoLegSecurityAltID, true }, // NUMINGROUP (spec has STRING - see note above)
        { FixField.FIX_NoLegStipulations, true }, // NUMINGROUP
        { FixField.FIX_NoLegs, true }, // NUMINGROUP
        { FixField.FIX_NoLinesOfText, true }, // NUMINGROUP
        { FixField.FIX_NoLotTypeRules, true }, // NUMINGROUP
        { FixField.FIX_NoMDEntries, true }, // NUMINGROUP
        { FixField.FIX_NoMDEntryTypes, true }, // NUMINGROUP
        { FixField.FIX_NoMDFeedTypes, true }, // NUMINGROUP
        { FixField.FIX_NoMarketSegments, true }, // NUMINGROUP
        { FixField.FIX_NoMatchRules, true }, // NUMINGROUP
        { FixField.FIX_NoMaturityRules, true }, // NUMINGROUP
        { FixField.FIX_NoMiscFees, true }, // NUMINGROUP
        { FixField.FIX_NoMsgTypes, true }, // NUMINGROUP
        { FixField.FIX_NoNested2PartyIDs, true }, // NUMINGROUP
        { FixField.FIX_NoNested2PartySubIDs, true }, // NUMINGROUP
        { FixField.FIX_NoNested3PartyIDs, true }, // NUMINGROUP
        { FixField.FIX_NoNested3PartySubIDs, true }, // NUMINGROUP
        { FixField.FIX_NoNested4PartyIDs, true }, // NUMINGROUP
        { FixField.FIX_NoNested4PartySubIDs, true }, // NUMINGROUP
        { FixField.FIX_NoNestedInstrAttrib, true }, // NUMINGROUP
        { FixField.FIX_NoNestedPartyIDs, true }, // NUMINGROUP
        { FixField.FIX_NoNestedPartySubIDs, true }, // NUMINGROUP
        { FixField.FIX_NoNewsRefIDs, true }, // NUMINGROUP
        { FixField.FIX_NoNotAffectedOrders, true }, // NUMINGROUP
        { FixField.FIX_NoOfLegUnderlyings, true }, // NUMINGROUP
        { FixField.FIX_NoOfSecSizes, true }, // NUMINGROUP
        { FixField.FIX_NoOrdTypeRules, true }, // NUMINGROUP
        { FixField.FIX_NoOrders, true }, // NUMINGROUP
        { FixField.FIX_NoPartyIDs, true }, // NUMINGROUP
        { FixField.FIX_NoPartySubIDs, true }, // NUMINGROUP
        { FixField.FIX_NoPosAmt, true }, // NUMINGROUP
        { FixField.FIX_NoPositions, true }, // NUMINGROUP
        { FixField.FIX_NoQuoteEntries, true }, // NUMINGROUP
        { FixField.FIX_NoQuoteQualifiers, true }, // NUMINGROUP
        { FixField.FIX_NoQuoteSets, true }, // NUMINGROUP
        { FixField.FIX_NoRateSources, true }, // NUMINGROUP
        { FixField.FIX_NoRegistDtls, true }, // NUMINGROUP
        { FixField.FIX_NoRelatedSym, true }, // NUMINGROUP
        { FixField.FIX_NoRootPartyIDs, true }, // NUMINGROUP
        { FixField.FIX_NoRootPartySubIDs, true }, // NUMINGROUP
        { FixField.FIX_NoRoutingIDs, true }, // NUMINGROUP
        { FixField.FIX_NoRpts, true }, // INT
        { FixField.FIX_NoSecurityAltID, true }, // NUMINGROUP
        { FixField.FIX_NoSecurityTypes, true }, // NUMINGROUP
        { FixField.FIX_NoSettlDetails, true }, // NUMINGROUP
        { FixField.FIX_NoSettlInst, true }, // NUMINGROUP
        { FixField.FIX_NoSettlOblig, true }, // NUMINGROUP
        { FixField.FIX_NoSettlPartyIDs, true }, // NUMINGROUP
        { FixField.FIX_NoSettlPartySubIDs, true }, // NUMINGROUP
        { FixField.FIX_NoSideTrdRegTS, true }, // NUMINGROUP
        { FixField.FIX_NoSides, true }, // NUMINGROUP
        { FixField.FIX_NoStatsIndicators, true }, // NUMINGROUP
        { FixField.FIX_NoStipulations, true }, // NUMINGROUP
        { FixField.FIX_NoStrategyParameters, true }, // NUMINGROUP
        { FixField.FIX_NoStrikeRules, true }, // NUMINGROUP
        { FixField.FIX_NoStrikes, true }, // NUMINGROUP
        { FixField.FIX_NoTargetPartyIDs, true }, // NUMINGROUP
        { FixField.FIX_NoTickRules, true }, // NUMINGROUP
        { FixField.FIX_NoTimeInForceRules, true }, // NUMINGROUP
        { FixField.FIX_NoTrades, true }, // NUMINGROUP
        { FixField.FIX_NoTradingSessionRules, true }, // NUMINGROUP
        { FixField.FIX_NoTradingSessions, true }, // NUMINGROUP
        { FixField.FIX_NoTrdRegTimestamps, true }, // NUMINGROUP
        { FixField.FIX_NoTrdRepIndicators, true }, // NUMINGROUP
        { FixField.FIX_NoUnderlyingAmounts, true }, // NUMINGROUP
        { FixField.FIX_NoUnderlyingLegSecurityAltID, true }, // NUMINGROUP
        { FixField.FIX_NoUnderlyingSecurityAltID, true }, // NUMINGROUP
        { FixField.FIX_NoUnderlyingStips, true }, // NUMINGROUP
        { FixField.FIX_NoUnderlyings, true }, // NUMINGROUP
        { FixField.FIX_NoUndlyInstrumentParties, true }, // NUMINGROUP
        { FixField.FIX_NoUndlyInstrumentPartySubIDs, true }, // NUMINGROUP
        { FixField.FIX_NotAffOrigClOrdID, false }, // STRING
        { FixField.FIX_NotAffectedOrderID, false }, // STRING
        { FixField.FIX_NotifyBrokerOfCredit, false }, // BOOLEAN
        { FixField.FIX_NotionalPercentageOutstanding, true }, // PERCENTAGE
        { FixField.FIX_NumBidders, true }, // INT
        { FixField.FIX_NumDaysInterest, true }, // INT
        { FixField.FIX_NumTickets, true }, // INT
        { FixField.FIX_NumberOfOrders, true }, // INT
        { FixField.FIX_OddLot, false }, // BOOLEAN
        { FixField.FIX_OfferForwardPoints, true }, // PRICEOFFSET
        { FixField.FIX_OfferForwardPoints2, true }, // PRICEOFFSET
        { FixField.FIX_OfferPx, true }, // PRICE
        { FixField.FIX_OfferSize, true }, // QTY
        { FixField.FIX_OfferSpotRate, true }, // PRICE
        { FixField.FIX_OfferSwapPoints, true }, // PRICEOFFSET
        { FixField.FIX_OfferYield, true }, // PERCENTAGE
        { FixField.FIX_OnBehalfOfCompID, false }, // STRING
        { FixField.FIX_OnBehalfOfLocationID, false }, // STRING
        { FixField.FIX_OnBehalfOfSubID, false }, // STRING
        { FixField.FIX_OpenCloseSettlFlag, false }, // MULTIPLECHARVALUE
        { FixField.FIX_OpenInterest, true }, // AMT
        { FixField.FIX_OptAttribute, false }, // CHAR
        { FixField.FIX_OptPayoutAmount, true }, // AMT
        { FixField.FIX_OptPayoutType, true }, // INT
        { FixField.FIX_OrdRejReason, true }, // INT
        { FixField.FIX_OrdStatus, false }, // CHAR
        { FixField.FIX_OrdStatusReqID, false }, // STRING
        { FixField.FIX_OrdType, false }, // CHAR
        { FixField.FIX_OrderAvgPx, true }, // PRICE
        { FixField.FIX_OrderBookingQty, true }, // QTY
        { FixField.FIX_OrderCapacity, false }, // CHAR
        { FixField.FIX_OrderCapacityQty, true }, // QTY
        { FixField.FIX_OrderCategory, false }, // CHAR
        { FixField.FIX_OrderDelay, true }, // INT
        { FixField.FIX_OrderDelayUnit, true }, // INT
        { FixField.FIX_OrderHandlingInstSource, true }, // INT
        { FixField.FIX_OrderID, false }, // STRING
        { FixField.FIX_OrderInputDevice, false }, // STRING
        { FixField.FIX_OrderPercent, true }, // PERCENTAGE
        { FixField.FIX_OrderQty, true }, // QTY
        { FixField.FIX_OrderQty2, true }, // QTY
        { FixField.FIX_OrderRestrictions, false }, // MULTIPLECHARVALUE
        { FixField.FIX_OrigClOrdID, false }, // STRING
        { FixField.FIX_OrigCrossID, false }, // STRING
        { FixField.FIX_OrigCustOrderCapacity, true }, // INT
        { FixField.FIX_OrigOrdModTime, false }, // UTCTIMESTAMP
        { FixField.FIX_OrigPosReqRefID, false }, // STRING
        { FixField.FIX_OrigSecondaryTradeID, false }, // STRING
        { FixField.FIX_OrigSendingTime, false }, // UTCTIMESTAMP
        { FixField.FIX_OrigTime, false }, // UTCTIMESTAMP
        { FixField.FIX_OrigTradeDate, false }, // LOCALMKTDATE
        { FixField.FIX_OrigTradeHandlingInstr, false }, // CHAR
        { FixField.FIX_OrigTradeID, false }, // STRING
        { FixField.FIX_OriginalNotionalPercentageOutstanding, true }, // PERCENTAGE
        { FixField.FIX_OutMainCntryUIndex, true }, // AMT
        { FixField.FIX_OutsideIndexPct, true }, // PERCENTAGE
        { FixField.FIX_OwnerType, true }, // INT
        { FixField.FIX_OwnershipType, false }, // CHAR
        { FixField.FIX_ParentMktSegmID, false }, // STRING
        { FixField.FIX_ParticipationRate, true }, // PERCENTAGE
        { FixField.FIX_PartyID, false }, // STRING
        { FixField.FIX_PartyIDSource, false }, // CHAR
        { FixField.FIX_PartyRole, true }, // INT
        { FixField.FIX_PartySubID, false }, // STRING
        { FixField.FIX_PartySubIDType, true }, // INT
        { FixField.FIX_Password, false }, // STRING
        { FixField.FIX_PaymentDate, false }, // LOCALMKTDATE
        { FixField.FIX_PaymentMethod, true }, // INT
        { FixField.FIX_PaymentRef, false }, // STRING
        { FixField.FIX_PaymentRemitterID, false }, // STRING
        { FixField.FIX_PctAtRisk, true }, // PERCENTAGE
        { FixField.FIX_PegLimitType, true }, // INT
        { FixField.FIX_PegMoveType, true }, // INT
        { FixField.FIX_PegOffsetType, true }, // INT
        { FixField.FIX_PegOffsetValue, true }, // FLOAT
        { FixField.FIX_PegPriceType, true }, // INT
        { FixField.FIX_PegRoundDirection, true }, // INT
        { FixField.FIX_PegScope, true }, // INT
        { FixField.FIX_PegSecurityDesc, false }, // STRING
        { FixField.FIX_PegSecurityID, false }, // STRING
        { FixField.FIX_PegSecurityIDSource, false }, // STRING
        { FixField.FIX_PegSymbol, false }, // STRING
        { FixField.FIX_PeggedPrice, true }, // PRICE
        { FixField.FIX_PeggedRefPrice, true }, // PRICE
        { FixField.FIX_Pool, false }, // STRING
        { FixField.FIX_PosAmt, true }, // AMT
        { FixField.FIX_PosAmtType, false }, // STRING
        { FixField.FIX_PosMaintAction, true }, // INT
        { FixField.FIX_PosMaintResult, true }, // INT
        { FixField.FIX_PosMaintRptID, false }, // STRING
        { FixField.FIX_PosMaintRptRefID, false }, // STRING
        { FixField.FIX_PosMaintStatus, true }, // INT
        { FixField.FIX_PosQtyStatus, true }, // INT
        { FixField.FIX_PosReqID, false }, // STRING
        { FixField.FIX_PosReqResult, true }, // INT
        { FixField.FIX_PosReqStatus, true }, // INT
        { FixField.FIX_PosReqType, true }, // INT
        { FixField.FIX_PosTransType, true }, // INT
        { FixField.FIX_PosType, false }, // STRING
        { FixField.FIX_PositionCurrency, false }, // STRING
        { FixField.FIX_PositionEffect, false }, // CHAR
        { FixField.FIX_PositionLimit, true }, // INT
        { FixField.FIX_PossDupFlag, false }, // BOOLEAN
        { FixField.FIX_PossResend, false }, // BOOLEAN
        { FixField.FIX_PreTradeAnonymity, false }, // BOOLEAN
        { FixField.FIX_PreallocMethod, false }, // CHAR
        { FixField.FIX_PrevClosePx, true }, // PRICE
        { FixField.FIX_PreviouslyReported, false }, // BOOLEAN
        { FixField.FIX_Price, true }, // PRICE
        { FixField.FIX_Price2, true }, // PRICE
        { FixField.FIX_PriceDelta, true }, // FLOAT
        { FixField.FIX_PriceImprovement, true }, // PRICEOFFSET
        { FixField.FIX_PriceLimitType, true }, // INT
        { FixField.FIX_PriceProtectionScope, false }, // CHAR
        { FixField.FIX_PriceQuoteMethod, false }, // STRING
        { FixField.FIX_PriceType, true }, // INT
        { FixField.FIX_PriceUnitOfMeasure, false }, // STRING
        { FixField.FIX_PriceUnitOfMeasureQty, true }, // QTY
        { FixField.FIX_PriorSettlPrice, true }, // PRICE
        { FixField.FIX_PriorSpreadIndicator, false }, // BOOLEAN
        { FixField.FIX_PriorityIndicator, true }, // INT
        { FixField.FIX_PrivateQuote, false }, // BOOLEAN
        { FixField.FIX_ProcessCode, false }, // CHAR
        { FixField.FIX_Product, true }, // INT
        { FixField.FIX_ProductComplex, false }, // STRING
        { FixField.FIX_ProgPeriodInterval, true }, // INT
        { FixField.FIX_ProgRptReqs, true }, // INT
        { FixField.FIX_PublishTrdIndicator, false }, // BOOLEAN
        { FixField.FIX_PutOrCall, true }, // INT
        { FixField.FIX_QtyType, true }, // INT
        { FixField.FIX_Quantity, true }, // QTY
        { FixField.FIX_QuantityDate, false }, // LOCALMKTDATE
        { FixField.FIX_QuoteCancelType, true }, // INT
        { FixField.FIX_QuoteCondition, false }, // MULTIPLESTRINGVALUE
        { FixField.FIX_QuoteEntryID, false }, // STRING
        { FixField.FIX_QuoteEntryRejectReason, true }, // INT
        { FixField.FIX_QuoteEntryStatus, true }, // INT
        { FixField.FIX_QuoteID, false }, // STRING
        { FixField.FIX_QuoteMsgID, false }, // STRING
        { FixField.FIX_QuotePriceType, true }, // INT
        { FixField.FIX_QuoteQualifier, false }, // CHAR
        { FixField.FIX_QuoteRejectReason, true }, // INT
        { FixField.FIX_QuoteReqID, false }, // STRING
        { FixField.FIX_QuoteRequestRejectReason, true }, // INT
        { FixField.FIX_QuoteRequestType, true }, // INT
        { FixField.FIX_QuoteRespID, false }, // STRING
        { FixField.FIX_QuoteRespType, true }, // INT
        { FixField.FIX_QuoteResponseLevel, true }, // INT
        { FixField.FIX_QuoteSetID, false }, // STRING
        { FixField.FIX_QuoteSetValidUntilTime, false }, // UTCTIMESTAMP
        { FixField.FIX_QuoteStatus, true }, // INT
        { FixField.FIX_QuoteStatusReqID, false }, // STRING
        { FixField.FIX_QuoteType, true }, // INT
        { FixField.FIX_RFQReqID, false }, // STRING
        { FixField.FIX_RateSource, true }, // INT
        { FixField.FIX_RateSourceType, true }, // INT
        { FixField.FIX_RawData, false }, // DATA
        { FixField.FIX_RawDataLength, true }, // LENGTH
        { FixField.FIX_ReceivedDeptID, false }, // STRING
        { FixField.FIX_RedemptionDate, false }, // LOCALMKTDATE
        { FixField.FIX_RefAllocID, false }, // STRING
        { FixField.FIX_RefApplExtID, true }, // INT
        { FixField.FIX_RefApplID, false }, // STRING
        { FixField.FIX_RefApplLastSeqNum, true }, // SEQNUM
        { FixField.FIX_RefApplReqID, false }, // STRING
        { FixField.FIX_RefApplVerID, false }, // STRING
        { FixField.FIX_RefCompID, false }, // STRING
        { FixField.FIX_RefCstmApplVerID, false }, // STRING
        { FixField.FIX_RefMsgType, false }, // STRING
        { FixField.FIX_RefOrdIDReason, true }, // INT
        { FixField.FIX_RefOrderID, false }, // STRING
        { FixField.FIX_RefOrderIDSource, false }, // CHAR
        { FixField.FIX_RefSeqNum, true }, // SEQNUM
        { FixField.FIX_RefSubID, false }, // STRING
        { FixField.FIX_RefTagID, true }, // INT
        { FixField.FIX_ReferencePage, false }, // STRING
        { FixField.FIX_RefreshIndicator, false }, // BOOLEAN
        { FixField.FIX_RefreshQty, true }, // QTY
        { FixField.FIX_RegistAcctType, false }, // STRING
        { FixField.FIX_RegistDtls, false }, // STRING
        { FixField.FIX_RegistEmail, false }, // STRING
        { FixField.FIX_RegistID, false }, // STRING
        { FixField.FIX_RegistRefID, false }, // STRING
        { FixField.FIX_RegistRejReasonCode, true }, // INT
        { FixField.FIX_RegistRejReasonText, false }, // STRING
        { FixField.FIX_RegistStatus, false }, // CHAR
        { FixField.FIX_RegistTransType, false }, // CHAR
        { FixField.FIX_RejectText, false }, // STRING
        { FixField.FIX_RelSymTransactTime, false }, // UTCTIMESTAMP
        { FixField.FIX_RepoCollateralSecurityType, true }, // INT
        { FixField.FIX_ReportToExch, false }, // BOOLEAN
        { FixField.FIX_ReportedPx, true }, // PRICE
        { FixField.FIX_ReportedPxDiff, false }, // BOOLEAN
        { FixField.FIX_RepurchaseRate, true }, // PERCENTAGE
        { FixField.FIX_RepurchaseTerm, true }, // INT
        { FixField.FIX_ResetSeqNumFlag, false }, // BOOLEAN
        { FixField.FIX_RespondentType, true }, // INT
        { FixField.FIX_ResponseDestination, false }, // STRING
        { FixField.FIX_ResponseTransportType, true }, // INT
        { FixField.FIX_RestructuringType, false }, // STRING
        { FixField.FIX_ReversalIndicator, false }, // BOOLEAN
        { FixField.FIX_RiskFreeRate, true }, // FLOAT
        { FixField.FIX_RndPx, true }, // PRICE
        { FixField.FIX_RootPartyID, false }, // STRING
        { FixField.FIX_RootPartyIDSource, false }, // CHAR
        { FixField.FIX_RootPartyRole, true }, // INT
        { FixField.FIX_RootPartySubID, false }, // STRING
        { FixField.FIX_RootPartySubIDType, true }, // INT
        { FixField.FIX_RoundLot, true }, // QTY
        { FixField.FIX_RoundingDirection, false }, // CHAR
        { FixField.FIX_RoundingModulus, true }, // FLOAT
        { FixField.FIX_RoutingID, false }, // STRING
        { FixField.FIX_RoutingType, true }, // INT
        { FixField.FIX_RptSeq, true }, // INT
        { FixField.FIX_RptSys, false }, // STRING
        { FixField.FIX_Scope, false }, // MULTIPLECHARVALUE
        { FixField.FIX_SecondaryAllocID, false }, // STRING
        { FixField.FIX_SecondaryClOrdID, false }, // STRING
        { FixField.FIX_SecondaryDisplayQty, true }, // QTY
        { FixField.FIX_SecondaryExecID, false }, // STRING
        { FixField.FIX_SecondaryFirmTradeID, false }, // STRING
        { FixField.FIX_SecondaryHighLimitPrice, true }, // PRICE
        { FixField.FIX_SecondaryIndividualAllocID, false }, // STRING
        { FixField.FIX_SecondaryLowLimitPrice, true }, // PRICE
        { FixField.FIX_SecondaryOrderID, false }, // STRING
        { FixField.FIX_SecondaryPriceLimitType, true }, // INT
        { FixField.FIX_SecondaryTradeID, false }, // STRING
        { FixField.FIX_SecondaryTradeReportID, false }, // STRING
        { FixField.FIX_SecondaryTradeReportRefID, false }, // STRING
        { FixField.FIX_SecondaryTradingReferencePrice, true }, // PRICE
        { FixField.FIX_SecondaryTrdType, true }, // INT
        { FixField.FIX_SecureData, false }, // DATA
        { FixField.FIX_SecureDataLen, true }, // LENGTH
        { FixField.FIX_SecurityAltID, false }, // STRING
        { FixField.FIX_SecurityAltIDSource, false }, // STRING
        { FixField.FIX_SecurityDesc, false }, // STRING
        { FixField.FIX_SecurityExchange, false }, // EXCHANGE
        { FixField.FIX_SecurityGroup, false }, // STRING
        { FixField.FIX_SecurityID, false }, // STRING
        { FixField.FIX_SecurityIDSource, false }, // STRING
        { FixField.FIX_SecurityListDesc, false }, // STRING
        { FixField.FIX_SecurityListID, false }, // STRING
        { FixField.FIX_SecurityListRefID, false }, // STRING
        { FixField.FIX_SecurityListRequestType, true }, // INT
        { FixField.FIX_SecurityListType, true }, // INT
        { FixField.FIX_SecurityListTypeSource, true }, // INT
        { FixField.FIX_SecurityReportID, true }, // INT
        { FixField.FIX_SecurityReqID, false }, // STRING
        { FixField.FIX_SecurityRequestResult, true }, // INT
        { FixField.FIX_SecurityRequestType, true }, // INT
        { FixField.FIX_SecurityResponseID, false }, // STRING
        { FixField.FIX_SecurityResponseType, true }, // INT
        { FixField.FIX_SecurityStatus, false }, // STRING
        { FixField.FIX_SecurityStatusReqID, false }, // STRING
        { FixField.FIX_SecuritySubType, false }, // STRING
        { FixField.FIX_SecurityTradingEvent, true }, // INT
        { FixField.FIX_SecurityTradingStatus, true }, // INT
        { FixField.FIX_SecurityType, false }, // STRING
        { FixField.FIX_SecurityUpdateAction, false }, // CHAR
        { FixField.FIX_SecurityXML, false }, // XMLDATA
        { FixField.FIX_SecurityXMLLen, true }, // LENGTH
        { FixField.FIX_SecurityXMLSchema, false }, // STRING
        { FixField.FIX_SellVolume, true }, // QTY
        { FixField.FIX_SellerDays, true }, // INT
        { FixField.FIX_SenderCompID, false }, // STRING
        { FixField.FIX_SenderLocationID, false }, // STRING
        { FixField.FIX_SenderSubID, false }, // STRING
        { FixField.FIX_SendingTime, false }, // UTCTIMESTAMP
        { FixField.FIX_Seniority, false }, // STRING
        { FixField.FIX_SessionRejectReason, true }, // INT
        { FixField.FIX_SessionStatus, true }, // INT
        { FixField.FIX_SettlCurrAmt, true }, // AMT
        { FixField.FIX_SettlCurrBidFxRate, true }, // FLOAT
        { FixField.FIX_SettlCurrFxRate, true }, // FLOAT
        { FixField.FIX_SettlCurrFxRateCalc, false }, // CHAR
        { FixField.FIX_SettlCurrOfferFxRate, true }, // FLOAT
        { FixField.FIX_SettlCurrency, false }, // CURRENCY
        { FixField.FIX_SettlDate, false }, // LOCALMKTDATE
        { FixField.FIX_SettlDate2, false }, // LOCALMKTDATE
        { FixField.FIX_SettlDeliveryType, true }, // INT
        { FixField.FIX_SettlInstID, false }, // STRING
        { FixField.FIX_SettlInstMode, false }, // CHAR
        { FixField.FIX_SettlInstMsgID, false }, // STRING
        { FixField.FIX_SettlInstRefID, false }, // STRING
        { FixField.FIX_SettlInstReqID, false }, // STRING
        { FixField.FIX_SettlInstReqRejCode, true }, // INT
        { FixField.FIX_SettlInstSource, false }, // CHAR
        { FixField.FIX_SettlInstTransType, false }, // CHAR
        { FixField.FIX_SettlMethod, false }, // CHAR
        { FixField.FIX_SettlObligID, false }, // STRING
        { FixField.FIX_SettlObligMode, true }, // INT
        { FixField.FIX_SettlObligMsgID, false }, // STRING
        { FixField.FIX_SettlObligRefID, false }, // STRING
        { FixField.FIX_SettlObligSource, false }, // CHAR
        { FixField.FIX_SettlObligTransType, false }, // CHAR
        { FixField.FIX_SettlPartyID, false }, // STRING
        { FixField.FIX_SettlPartyIDSource, false }, // CHAR
        { FixField.FIX_SettlPartyRole, true }, // INT
        { FixField.FIX_SettlPartySubID, false }, // STRING
        { FixField.FIX_SettlPartySubIDType, true }, // INT
        { FixField.FIX_SettlPrice, true }, // PRICE
        { FixField.FIX_SettlPriceType, true }, // INT
        { FixField.FIX_SettlSessID, false }, // STRING
        { FixField.FIX_SettlSessSubID, false }, // STRING
        { FixField.FIX_SettlType, false }, // STRING
        { FixField.FIX_SettleOnOpenFlag, false }, // STRING
        { FixField.FIX_SettlementCycleNo, true }, // INT
        { FixField.FIX_SharedCommission, true }, // AMT
        { FixField.FIX_ShortQty, true }, // QTY
        { FixField.FIX_ShortSaleReason, true }, // INT
        { FixField.FIX_Side, false }, // CHAR
        { FixField.FIX_SideComplianceID, false }, // STRING
        { FixField.FIX_SideCurrency, false }, // CURRENCY
        { FixField.FIX_SideExecID, false }, // STRING
        { FixField.FIX_SideFillStationCd, false }, // STRING
        { FixField.FIX_SideGrossTradeAmt, true }, // AMT
        { FixField.FIX_SideLastQty, true }, // INT
        { FixField.FIX_SideLiquidityInd, true }, // INT
        { FixField.FIX_SideMultiLegReportingType, true }, // INT
        { FixField.FIX_SideReasonCd, false }, // STRING
        { FixField.FIX_SideSettlCurrency, false }, // CURRENCY
        { FixField.FIX_SideTimeInForce, false }, // UTCTIMESTAMP
        { FixField.FIX_SideTradeReportID, false }, // STRING
        { FixField.FIX_SideTrdRegTimestamp, false }, // UTCTIMESTAMP
        { FixField.FIX_SideTrdRegTimestampSrc, false }, // STRING
        { FixField.FIX_SideTrdRegTimestampType, true }, // INT
        { FixField.FIX_SideTrdSubTyp, true }, // INT
        { FixField.FIX_SideValue1, true }, // AMT
        { FixField.FIX_SideValue2, true }, // AMT
        { FixField.FIX_SideValueInd, true }, // INT
        { FixField.FIX_Signature, false }, // DATA
        { FixField.FIX_SignatureLength, true }, // LENGTH
        { FixField.FIX_SolicitedFlag, false }, // BOOLEAN
        { FixField.FIX_Spread, true }, // PRICEOFFSET
        { FixField.FIX_StandInstDbID, false }, // STRING
        { FixField.FIX_StandInstDbName, false }, // STRING
        { FixField.FIX_StandInstDbType, true }, // INT
        { FixField.FIX_StartCash, true }, // AMT
        { FixField.FIX_StartDate, false }, // LOCALMKTDATE
        { FixField.FIX_StartMaturityMonthYear, false }, // MONTHYEAR
        { FixField.FIX_StartStrikePxRange, true }, // PRICE
        { FixField.FIX_StartTickPriceRange, true }, // PRICE
        { FixField.FIX_StateOrProvinceOfIssue, false }, // STRING
        { FixField.FIX_StatsType, true }, // INT
        { FixField.FIX_StatusText, false }, // STRING
        { FixField.FIX_StatusValue, true }, // INT
        { FixField.FIX_StipulationType, false }, // STRING
        { FixField.FIX_StipulationValue, false }, // STRING
        { FixField.FIX_StopPx, true }, // PRICE
        { FixField.FIX_StrategyParameterName, false }, // STRING
        { FixField.FIX_StrategyParameterType, true }, // INT
        { FixField.FIX_StrategyParameterValue, false }, // STRING
        { FixField.FIX_StreamAsgnAckType, true }, // INT
        { FixField.FIX_StreamAsgnRejReason, true }, // INT
        { FixField.FIX_StreamAsgnReqID, false }, // STRING
        { FixField.FIX_StreamAsgnReqType, true }, // INT
        { FixField.FIX_StreamAsgnRptID, false }, // STRING
        { FixField.FIX_StreamAsgnType, true }, // INT
        { FixField.FIX_StrikeCurrency, false }, // CURRENCY
        { FixField.FIX_StrikeExerciseStyle, true }, // INT
        { FixField.FIX_StrikeIncrement, true }, // FLOAT
        { FixField.FIX_StrikeMultiplier, true }, // FLOAT
        { FixField.FIX_StrikePrice, true }, // PRICE
        { FixField.FIX_StrikePriceBoundaryMethod, true }, // INT
        { FixField.FIX_StrikePriceBoundaryPrecision, true }, // PERCENTAGE
        { FixField.FIX_StrikePriceDeterminationMethod, true }, // INT
        { FixField.FIX_StrikeRuleID, false }, // STRING
        { FixField.FIX_StrikeTime, false }, // UTCTIMESTAMP
        { FixField.FIX_StrikeValue, true }, // FLOAT
        { FixField.FIX_Subject, false }, // STRING
        { FixField.FIX_SubscriptionRequestType, false }, // CHAR
        { FixField.FIX_SwapPoints, true }, // PRICEOFFSET
        { FixField.FIX_Symbol, false }, // STRING
        { FixField.FIX_SymbolSfx, false }, // STRING
        { FixField.FIX_TZTransactTime, false }, // TZTIMESTAMP
        { FixField.FIX_TargetCompID, false }, // STRING
        { FixField.FIX_TargetLocationID, false }, // STRING
        { FixField.FIX_TargetPartyID, false }, // STRING
        { FixField.FIX_TargetPartyIDSource, false }, // CHAR
        { FixField.FIX_TargetPartyRole, true }, // INT
        { FixField.FIX_TargetStrategy, true }, // INT
        { FixField.FIX_TargetStrategyParameters, false }, // STRING
        { FixField.FIX_TargetStrategyPerformance, true }, // FLOAT
        { FixField.FIX_TargetSubID, false }, // STRING
        { FixField.FIX_TaxAdvantageType, true }, // INT
        { FixField.FIX_TerminationType, true }, // INT
        { FixField.FIX_TestMessageIndicator, false }, // BOOLEAN
        { FixField.FIX_TestReqID, false }, // STRING
        { FixField.FIX_Text, false }, // STRING
        { FixField.FIX_ThresholdAmount, true }, // PRICEOFFSET
        { FixField.FIX_TickDirection, false }, // CHAR
        { FixField.FIX_TickIncrement, true }, // PRICE
        { FixField.FIX_TickRuleType, true }, // INT
        { FixField.FIX_TierCode, false }, // STRING
        { FixField.FIX_TimeBracket, false }, // STRING
        { FixField.FIX_TimeInForce, false }, // CHAR
        { FixField.FIX_TimeToExpiration, true }, // FLOAT
        { FixField.FIX_TimeUnit, false }, // STRING
        { FixField.FIX_TotNoAccQuotes, true }, // INT
        { FixField.FIX_TotNoAllocs, true }, // INT
        { FixField.FIX_TotNoCxldQuotes, true }, // INT
        { FixField.FIX_TotNoFills, true }, // INT
        { FixField.FIX_TotNoOrders, true }, // INT
        { FixField.FIX_TotNoQuoteEntries, true }, // INT
        { FixField.FIX_TotNoRejQuotes, true }, // INT
        { FixField.FIX_TotNoRelatedSym, true }, // INT
        { FixField.FIX_TotNoSecurityTypes, true }, // INT
        { FixField.FIX_TotNoStrikes, true }, // INT
        { FixField.FIX_TotNumAssignmentReports, true }, // INT
        { FixField.FIX_TotNumReports, true }, // INT
        { FixField.FIX_TotNumTradeReports, true }, // INT
        { FixField.FIX_TotalAccruedInterestAmt, true }, // AMT
        { FixField.FIX_TotalAffectedOrders, true }, // INT
        { FixField.FIX_TotalNetValue, true }, // AMT
        { FixField.FIX_TotalNumPosReports, true }, // INT
        { FixField.FIX_TotalTakedown, true }, // AMT
        { FixField.FIX_TotalVolumeTraded, true }, // QTY
        { FixField.FIX_TradSesCloseTime, false }, // UTCTIMESTAMP
        { FixField.FIX_TradSesEndTime, false }, // UTCTIMESTAMP
        { FixField.FIX_TradSesEvent, true }, // INT
        { FixField.FIX_TradSesMethod, true }, // INT
        { FixField.FIX_TradSesMode, true }, // INT
        { FixField.FIX_TradSesOpenTime, false }, // UTCTIMESTAMP
        { FixField.FIX_TradSesPreCloseTime, false }, // UTCTIMESTAMP
        { FixField.FIX_TradSesReqID, false }, // STRING
        { FixField.FIX_TradSesStartTime, false }, // UTCTIMESTAMP
        { FixField.FIX_TradSesStatus, true }, // INT
        { FixField.FIX_TradSesStatusRejReason, true }, // INT
        { FixField.FIX_TradSesUpdateAction, false }, // CHAR
        { FixField.FIX_TradeAllocIndicator, true }, // INT
        { FixField.FIX_TradeCondition, false }, // MULTIPLESTRINGVALUE
        { FixField.FIX_TradeDate, false }, // LOCALMKTDATE
        { FixField.FIX_TradeHandlingInstr, false }, // CHAR
        { FixField.FIX_TradeID, false }, // STRING
        { FixField.FIX_TradeInputDevice, false }, // STRING
        { FixField.FIX_TradeInputSource, false }, // STRING
        { FixField.FIX_TradeLegRefID, false }, // STRING
        { FixField.FIX_TradeLinkID, false }, // STRING
        { FixField.FIX_TradeOriginationDate, false }, // LOCALMKTDATE
        { FixField.FIX_TradePublishIndicator, true }, // INT
        { FixField.FIX_TradeReportID, false }, // STRING
        { FixField.FIX_TradeReportRefID, false }, // STRING
        { FixField.FIX_TradeReportRejectReason, true }, // INT
        { FixField.FIX_TradeReportTransType, true }, // INT
        { FixField.FIX_TradeReportType, true }, // INT
        { FixField.FIX_TradeRequestID, false }, // STRING
        { FixField.FIX_TradeRequestResult, true }, // INT
        { FixField.FIX_TradeRequestStatus, true }, // INT
        { FixField.FIX_TradeRequestType, true }, // INT
        { FixField.FIX_TradeVolume, true }, // QTY
        { FixField.FIX_TradedFlatSwitch, false }, // BOOLEAN
        { FixField.FIX_TradingCurrency, false }, // CURRENCY
        { FixField.FIX_TradingReferencePrice, true }, // PRICE
        { FixField.FIX_TradingSessionDesc, false }, // STRING
        { FixField.FIX_TradingSessionID, false }, // STRING
        { FixField.FIX_TradingSessionSubID, false }, // STRING
        { FixField.FIX_TransBkdTime, false }, // UTCTIMESTAMP
        { FixField.FIX_TransactTime, false }, // UTCTIMESTAMP
        { FixField.FIX_TransferReason, false }, // STRING
        { FixField.FIX_TrdMatchID, false }, // STRING
        { FixField.FIX_TrdRegTimestamp, false }, // UTCTIMESTAMP
        { FixField.FIX_TrdRegTimestampOrigin, false }, // STRING
        { FixField.FIX_TrdRegTimestampType, true }, // INT
        { FixField.FIX_TrdRepIndicator, false }, // BOOLEAN
        { FixField.FIX_TrdRepPartyRole, true }, // INT
        { FixField.FIX_TrdRptStatus, true }, // INT
        { FixField.FIX_TrdSubType, true }, // INT
        { FixField.FIX_TrdType, true }, // INT
        { FixField.FIX_TriggerAction, false }, // CHAR
        { FixField.FIX_TriggerNewPrice, true }, // PRICE
        { FixField.FIX_TriggerNewQty, true }, // QTY
        { FixField.FIX_TriggerOrderType, false }, // CHAR
        { FixField.FIX_TriggerPrice, true }, // PRICE
        { FixField.FIX_TriggerPriceDirection, false }, // CHAR
        { FixField.FIX_TriggerPriceType, false }, // CHAR
        { FixField.FIX_TriggerPriceTypeScope, false }, // CHAR
        { FixField.FIX_TriggerSecurityDesc, false }, // STRING
        { FixField.FIX_TriggerSecurityID, false }, // STRING
        { FixField.FIX_TriggerSecurityIDSource, false }, // STRING
        { FixField.FIX_TriggerSymbol, false }, // STRING
        { FixField.FIX_TriggerTradingSessionID, false }, // STRING
        { FixField.FIX_TriggerTradingSessionSubID, false }, // STRING
        { FixField.FIX_TriggerType, false }, // CHAR
        { FixField.FIX_URLLink, false }, // STRING
        { FixField.FIX_UnderlyingAdjustedQuantity, true }, // QTY
        { FixField.FIX_UnderlyingAllocationPercent, true }, // PERCENTAGE
        { FixField.FIX_UnderlyingAttachmentPoint, true }, // PERCENTAGE
        { FixField.FIX_UnderlyingCFICode, false }, // STRING
        { FixField.FIX_UnderlyingCPProgram, false }, // STRING
        { FixField.FIX_UnderlyingCPRegType, false }, // STRING
        { FixField.FIX_UnderlyingCapValue, true }, // AMT
        { FixField.FIX_UnderlyingCashAmount, true }, // AMT
        { FixField.FIX_UnderlyingCashType, false }, // STRING
        { FixField.FIX_UnderlyingCollectAmount, true }, // AMT
        { FixField.FIX_UnderlyingContractMultiplier, true }, // FLOAT
        { FixField.FIX_UnderlyingContractMultiplierUnit, true }, // INT
        { FixField.FIX_UnderlyingCountryOfIssue, false }, // COUNTRY
        { FixField.FIX_UnderlyingCouponPaymentDate, false }, // LOCALMKTDATE
        { FixField.FIX_UnderlyingCouponRate, true }, // PERCENTAGE
        { FixField.FIX_UnderlyingCreditRating, false }, // STRING
        { FixField.FIX_UnderlyingCurrency, false }, // CURRENCY
        { FixField.FIX_UnderlyingCurrentValue, true }, // AMT
        { FixField.FIX_UnderlyingDeliveryAmount, true }, // AMT
        { FixField.FIX_UnderlyingDetachmentPoint, true }, // PERCENTAGE
        { FixField.FIX_UnderlyingDirtyPrice, true }, // PRICE
        { FixField.FIX_UnderlyingEndPrice, true }, // PRICE
        { FixField.FIX_UnderlyingEndValue, true }, // AMT
        { FixField.FIX_UnderlyingExerciseStyle, true }, // INT
        { FixField.FIX_UnderlyingFXRate, true }, // FLOAT
        { FixField.FIX_UnderlyingFXRateCalc, false }, // CHAR
        { FixField.FIX_UnderlyingFactor, true }, // FLOAT
        { FixField.FIX_UnderlyingFlowScheduleType, true }, // INT
        { FixField.FIX_UnderlyingInstrRegistry, false }, // STRING
        { FixField.FIX_UnderlyingInstrumentPartyID, false }, // STRING
        { FixField.FIX_UnderlyingInstrumentPartyIDSource, false }, // CHAR
        { FixField.FIX_UnderlyingInstrumentPartyRole, true }, // INT
        { FixField.FIX_UnderlyingInstrumentPartySubID, false }, // STRING
        { FixField.FIX_UnderlyingInstrumentPartySubIDType, true }, // INT
        { FixField.FIX_UnderlyingIssueDate, false }, // LOCALMKTDATE
        { FixField.FIX_UnderlyingIssuer, false }, // STRING
        { FixField.FIX_UnderlyingLastPx, true }, // PRICE
        { FixField.FIX_UnderlyingLastQty, true }, // QTY
        { FixField.FIX_UnderlyingLegCFICode, false }, // STRING
        { FixField.FIX_UnderlyingLegMaturityDate, false }, // LOCALMKTDATE
        { FixField.FIX_UnderlyingLegMaturityMonthYear, false }, // MONTHYEAR
        { FixField.FIX_UnderlyingLegMaturityTime, false }, // TZTIMEONLY
        { FixField.FIX_UnderlyingLegOptAttribute, false }, // CHAR
        { FixField.FIX_UnderlyingLegPutOrCall, true }, // INT
        { FixField.FIX_UnderlyingLegSecurityAltID, false }, // STRING
        { FixField.FIX_UnderlyingLegSecurityAltIDSource, false }, // STRING
        { FixField.FIX_UnderlyingLegSecurityDesc, false }, // STRING
        { FixField.FIX_UnderlyingLegSecurityExchange, false }, // STRING
        { FixField.FIX_UnderlyingLegSecurityID, false }, // STRING
        { FixField.FIX_UnderlyingLegSecurityIDSource, false }, // STRING
        { FixField.FIX_UnderlyingLegSecuritySubType, false }, // STRING
        { FixField.FIX_UnderlyingLegSecurityType, false }, // STRING
        { FixField.FIX_UnderlyingLegStrikePrice, true }, // PRICE
        { FixField.FIX_UnderlyingLegSymbol, false }, // STRING
        { FixField.FIX_UnderlyingLegSymbolSfx, false }, // STRING
        { FixField.FIX_UnderlyingLocaleOfIssue, false }, // STRING
        { FixField.FIX_UnderlyingMaturityDate, false }, // LOCALMKTDATE
        { FixField.FIX_UnderlyingMaturityMonthYear, false }, // MONTHYEAR
        { FixField.FIX_UnderlyingMaturityTime, false }, // TZTIMEONLY
        { FixField.FIX_UnderlyingNotionalPercentageOutstanding, true }, // PERCENTAGE
        { FixField.FIX_UnderlyingOptAttribute, false }, // CHAR
        { FixField.FIX_UnderlyingOriginalNotionalPercentageOutstanding, true }, // PERCENTAGE
        { FixField.FIX_UnderlyingPayAmount, true }, // AMT
        { FixField.FIX_UnderlyingPriceDeterminationMethod, true }, // INT
        { FixField.FIX_UnderlyingPriceUnitOfMeasure, false }, // STRING
        { FixField.FIX_UnderlyingPriceUnitOfMeasureQty, true }, // QTY
        { FixField.FIX_UnderlyingProduct, true }, // INT
        { FixField.FIX_UnderlyingPutOrCall, true }, // INT
        { FixField.FIX_UnderlyingPx, true }, // PRICE
        { FixField.FIX_UnderlyingQty, true }, // QTY
        { FixField.FIX_UnderlyingRedemptionDate, false }, // LOCALMKTDATE
        { FixField.FIX_UnderlyingRepoCollateralSecurityType, true }, // INT
        { FixField.FIX_UnderlyingRepurchaseRate, true }, // PERCENTAGE
        { FixField.FIX_UnderlyingRepurchaseTerm, true }, // INT
        { FixField.FIX_UnderlyingRestructuringType, false }, // STRING
        { FixField.FIX_UnderlyingSecurityAltID, false }, // STRING
        { FixField.FIX_UnderlyingSecurityAltIDSource, false }, // STRING
        { FixField.FIX_UnderlyingSecurityDesc, false }, // STRING
        { FixField.FIX_UnderlyingSecurityExchange, false }, // EXCHANGE
        { FixField.FIX_UnderlyingSecurityID, false }, // STRING
        { FixField.FIX_UnderlyingSecurityIDSource, false }, // STRING
        { FixField.FIX_UnderlyingSecuritySubType, false }, // STRING
        { FixField.FIX_UnderlyingSecurityType, false }, // STRING
        { FixField.FIX_UnderlyingSeniority, false }, // STRING
        { FixField.FIX_UnderlyingSettlMethod, false }, // STRING
        { FixField.FIX_UnderlyingSettlPrice, true }, // PRICE
        { FixField.FIX_UnderlyingSettlPriceType, true }, // INT
        { FixField.FIX_UnderlyingSettlementDate, false }, // LOCALMKTDATE
        { FixField.FIX_UnderlyingSettlementStatus, false }, // STRING
        { FixField.FIX_UnderlyingSettlementType, true }, // INT
        { FixField.FIX_UnderlyingStartValue, true }, // AMT
        { FixField.FIX_UnderlyingStateOrProvinceOfIssue, false }, // STRING
        { FixField.FIX_UnderlyingStipType, false }, // STRING
        { FixField.FIX_UnderlyingStipValue, false }, // STRING
        { FixField.FIX_UnderlyingStrikeCurrency, false }, // CURRENCY
        { FixField.FIX_UnderlyingStrikePrice, true }, // PRICE
        { FixField.FIX_UnderlyingSymbol, false }, // STRING
        { FixField.FIX_UnderlyingSymbolSfx, false }, // STRING
        { FixField.FIX_UnderlyingTimeUnit, false }, // STRING
        { FixField.FIX_UnderlyingTradingSessionID, false }, // STRING
        { FixField.FIX_UnderlyingTradingSessionSubID, false }, // STRING
        { FixField.FIX_UnderlyingUnitOfMeasure, false }, // STRING
        { FixField.FIX_UnderlyingUnitOfMeasureQty, true }, // QTY
        { FixField.FIX_UnitOfMeasure, false }, // STRING
        { FixField.FIX_UnitOfMeasureQty, true }, // QTY
        { FixField.FIX_UnsolicitedIndicator, false }, // BOOLEAN
        { FixField.FIX_Urgency, false }, // CHAR
        { FixField.FIX_UserRequestID, false }, // STRING
        { FixField.FIX_UserRequestType, true }, // INT
        { FixField.FIX_UserStatus, true }, // INT
        { FixField.FIX_UserStatusText, false }, // STRING
        { FixField.FIX_Username, false }, // STRING
        { FixField.FIX_ValidUntilTime, false }, // UTCTIMESTAMP
        { FixField.FIX_ValuationMethod, false }, // STRING
        { FixField.FIX_ValueOfFutures, true }, // AMT
        { FixField.FIX_VenueType, false }, // CHAR
        { FixField.FIX_Volatility, true }, // FLOAT
        { FixField.FIX_WorkingIndicator, false }, // BOOLEAN
        { FixField.FIX_WtAverageLiquidity, true }, // PERCENTAGE
        { FixField.FIX_XmlData, false }, // DATA
        { FixField.FIX_XmlDataLen, true }, // LENGTH
        { FixField.FIX_Yield, true }, // PERCENTAGE
        { FixField.FIX_YieldCalcDate, false }, // LOCALMKTDATE
        { FixField.FIX_YieldRedemptionDate, false }, // LOCALMKTDATE
        { FixField.FIX_YieldRedemptionPrice, true }, // PRICE
        { FixField.FIX_YieldRedemptionPriceType, true }, // INT
        { FixField.FIX_YieldType, false }, // STRING
    };

    /// <summary>
    /// Returns whether the given FIX field's data type is numeric per the FIX 5.0 SP2 field
    /// dictionary. Fields absent from the dictionary (not present in this repo's tag range, or
    /// removed in later specs) default to non-numeric - the safer default, since it never turns a
    /// string value into a misleading number.
    /// </summary>
    public static bool IsNumeric(FixField field) => IsNumericByField.GetValueOrDefault(field);
}
