name: coverage

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

concurrency:
  group: coverage-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  packages: read

jobs:
  coverage:
    uses: FixPortal/fixportal-workflows/.github/workflows/dotnet-coverage.yml@ea938eb59ea370d31d86e4fd1200b1a2dfcb3e39 # main
    with:
      solution: FixPortal.FixAtdl.slnx
